package gcm.test.automated;

import static gcm.test.support.EnvironmentSupport.getRandomGenerator;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.apache.commons.math3.random.RandomGenerator;
import org.apache.commons.math3.util.FastMath;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import gcm.test.support.SeedProvider;
import gcm.util.annotations.UnitTest;
import gcm.util.vector.MutableVector3D;
import gcm.util.vector.Vector3D;

/**
 * Test class for {@link Vector3D}
 * 
 * @author Shawn Hatch
 *
 */
@UnitTest(target = Vector3D.class)
public class AT_Vector3D {

	private static SeedProvider SEED_PROVIDER;

	private static final double TOLERANCE = 0.000001;

	@BeforeClass
	public static void beforeClass() {
		SEED_PROVIDER = new SeedProvider(45624564585678567L);
	}

	/**
	 * Internal test(not part of public tests) to show that there are no large
	 * gaps in the seed cases generated by the SeedProvider.
	 */
	@AfterClass
	public static void afterClass() {
		// System.out.println(AT_Vector3D.class.getSimpleName() + " " +
		// SEED_PROVIDER.generateUnusedSeedReport());
	}

	/**
	 * Tests {@linkplain Vector3D#add(Vector3D)}
	 * 
	 * Tests {@linkplain Vector3D#add(double, double, double)}
	 */
	@Test
	public void testAdd() {

		final long seed = SEED_PROVIDER.getSeedValue(0);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {
			double x1 = randomGenerator.nextDouble() * 1000 - 500;
			double y1 = randomGenerator.nextDouble() * 1000 - 500;
			double z1 = randomGenerator.nextDouble() * 1000 - 500;
			Vector3D v1 = new Vector3D(x1, y1, z1);

			double x2 = randomGenerator.nextDouble() * 1000 - 500;
			double y2 = randomGenerator.nextDouble() * 1000 - 500;
			double z2 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v2 = new Vector3D(x2, y2, z2);
			v1 = v1.add(v2);

			// Tests {@linkplain MutableVector3D#add(MutableVector3D)}
			assertEquals(x1 + x2, v1.getX(), 0);
			assertEquals(y1 + y2, v1.getY(), 0);
			assertEquals(z1 + z2, v1.getZ(), 0);

			v1 = new Vector3D(x1, y1, z1);
			v1 = v1.add(x2, y2, z2);

			// Tests {@linkplain Vector3D#add(double, double, double)}
			assertEquals(x1 + x2, v1.getX(), 0);
			assertEquals(y1 + y2, v1.getY(), 0);
			assertEquals(z1 + z2, v1.getZ(), 0);

			v1 = new Vector3D(x1, y1, z1);
			Vector3D v3 = new Vector3D(x2, y2, z2);
			v1 = v1.add(v3);

			// Tests {@linkplain Vector3D#add(Vector3D)}
			assertEquals(x1 + x2, v1.getX(), 0);
			assertEquals(y1 + y2, v1.getY(), 0);
			assertEquals(z1 + z2, v1.getZ(), 0);

		}
	}

	/**
	 * Tests {@linkplain Vector3D#Vector3D()}
	 * 
	 * Tests {@linkplain Vector3D#Vector3D(MutableVector3D)}
	 * 
	 * Tests {@linkplain Vector3D#Vector3D(Vector3D)}
	 * 
	 * Tests {@linkplain Vector3D#Vector3D(double, double, double)}
	 * 
	 */
	@Test
	public void testConstructors() {

		final long seed = SEED_PROVIDER.getSeedValue(1);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			Vector3D v = new Vector3D();

			// Tests {@linkplain Vector3D#Vector3D()}
			assertEquals(0, v.getX(), 0);
			assertEquals(0, v.getY(), 0);
			assertEquals(0, v.getZ(), 0);

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			v = new Vector3D(x, y, z);

			// Tests {@linkplain Vector3D#Vector3D(double, double, double)}
			assertEquals(x, v.getX(), 0);
			assertEquals(y, v.getY(), 0);
			assertEquals(z, v.getZ(), 0);

			MutableVector3D v2 = new MutableVector3D(v);

			// Tests {@linkplain Vector3D#Vector3D(MutableVector3D)}
			assertEquals(v.getX(), v2.getX(), 0);
			assertEquals(v.getY(), v2.getY(), 0);
			assertEquals(v.getZ(), v2.getZ(), 0);

			Vector3D v3 = new Vector3D(v);

			// Tests {@linkplain Vector3D#Vector3D(Vector3D)}
			assertEquals(v.getX(), v3.getX(), 0);
			assertEquals(v.getY(), v3.getY(), 0);
			assertEquals(v.getZ(), v3.getZ(), 0);
		}
	}

	/**
	 * Tests {@linkplain Vector3D#addScaled(MutableVector3D, double)}
	 * 
	 * Tests {@linkplain Vector3D#addScaled(Vector3D, double)}
	 * 
	 */
	@Test
	public void testAddScaled() {

		final long seed = SEED_PROVIDER.getSeedValue(2);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {
			double x1 = randomGenerator.nextDouble() * 1000 - 500;
			double y1 = randomGenerator.nextDouble() * 1000 - 500;
			double z1 = randomGenerator.nextDouble() * 1000 - 500;
			MutableVector3D v1 = new MutableVector3D(x1, y1, z1);

			double x2 = randomGenerator.nextDouble() * 1000 - 500;
			double y2 = randomGenerator.nextDouble() * 1000 - 500;
			double z2 = randomGenerator.nextDouble() * 1000 - 500;

			MutableVector3D v2 = new MutableVector3D(x2, y2, z2);

			double scale = randomGenerator.nextDouble() * 1000 - 500;

			v1.addScaled(v2, scale);

			// Tests {@linkplain Vector3D#addScaled(MutableVector3D, double)}
			assertEquals(x1 + x2 * scale, v1.getX(), 0);
			assertEquals(y1 + y2 * scale, v1.getY(), 0);
			assertEquals(z1 + z2 * scale, v1.getZ(), 0);

			v1.assign(x1, y1, z1);
			Vector3D v3 = new Vector3D(x2, y2, z2);
			scale = randomGenerator.nextDouble() * 1000 - 500;
			v1.addScaled(v3, scale);

			// Tests {@linkplain Vector3D#addScaled(Vector3D, double)}
			assertEquals(x1 + x2 * scale, v1.getX(), 0);
			assertEquals(y1 + y2 * scale, v1.getY(), 0);
			assertEquals(z1 + z2 * scale, v1.getZ(), 0);
		}
	}

	/**
	 * 
	 * Tests {@linkplain Vector3D#angle(Vector3D)}
	 * 
	 */
	@Test
	public void testAngle() {

		final long seed = SEED_PROVIDER.getSeedValue(3);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x1 = randomGenerator.nextDouble() * 1000 - 500;
			double y1 = randomGenerator.nextDouble() * 1000 - 500;
			double z1 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v1 = new Vector3D(x1, y1, z1);

			double x2 = randomGenerator.nextDouble() * 1000 - 500;
			double y2 = randomGenerator.nextDouble() * 1000 - 500;
			double z2 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v2 = new Vector3D(x2, y2, z2);

			double length1 = FastMath.sqrt(x1 * x1 + y1 * y1 + z1 * z1);
			double length2 = FastMath.sqrt(x2 * x2 + y2 * y2 + z2 * z2);
			double dotProduct = x1 * x2 + y1 * y2 + z1 * z2;
			double cosTheta = dotProduct / (length1 * length2);
			double expectedValue = FastMath.acos(cosTheta);

			double actualValue = v1.angle(v2);

			assertEquals(expectedValue, actualValue, TOLERANCE);

		}
	}

	/**
	 * Tests {@linkplain Vector3D#cross(Vector3D))}
	 */
	@Test
	public void testCross() {

		final long seed = SEED_PROVIDER.getSeedValue(5);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x1 = randomGenerator.nextDouble() * 1000 - 500;
			double y1 = randomGenerator.nextDouble() * 1000 - 500;
			double z1 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v1 = new Vector3D(x1, y1, z1);

			double x2 = randomGenerator.nextDouble() * 1000 - 500;
			double y2 = randomGenerator.nextDouble() * 1000 - 500;
			double z2 = randomGenerator.nextDouble() * 1000 - 500;

			MutableVector3D v2 = new MutableVector3D(x2, y2, z2);
			v2.cross(v1);

			double x3 = y2 * z1 - y1 * z2;
			double y3 = x1 * z2 - x2 * z1;
			double z3 = x2 * y1 - x1 * y2;

			assertEquals(x3, v2.getX(), TOLERANCE);
			assertEquals(y3, v2.getY(), TOLERANCE);
			assertEquals(z3, v2.getZ(), TOLERANCE);
		}
	}

	/**
	 * Tests {@linkplain Vector3D#distanceTo(Vector3D)}
	 */
	@Test
	public void testDistanceTo() {

		final long seed = SEED_PROVIDER.getSeedValue(6);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x1 = randomGenerator.nextDouble() * 1000 - 500;
			double y1 = randomGenerator.nextDouble() * 1000 - 500;
			double z1 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v1 = new Vector3D(x1, y1, z1);

			double x2 = randomGenerator.nextDouble() * 1000 - 500;
			double y2 = randomGenerator.nextDouble() * 1000 - 500;
			double z2 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v2 = new Vector3D(x2, y2, z2);

			double expected = FastMath.sqrt((x1 - x2) * (x1 - x2) + (y1 - y2) * (y1 - y2) + (z1 - z2) * (z1 - z2));

			double actual = v2.distanceTo(v1);

			// Tests {@linkplain MutableVector3D#distanceTo(MutableVector3D)}
			assertEquals(expected, actual, TOLERANCE);
		}
	}

	/**
	 * Tests {@linkplain Vector3D#dot(Vector3D)}
	 */
	@Test
	public void testDot() {

		final long seed = SEED_PROVIDER.getSeedValue(7);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x1 = randomGenerator.nextDouble() * 1000 - 500;
			double y1 = randomGenerator.nextDouble() * 1000 - 500;
			double z1 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v1 = new Vector3D(x1, y1, z1);

			double x2 = randomGenerator.nextDouble() * 1000 - 500;
			double y2 = randomGenerator.nextDouble() * 1000 - 500;
			double z2 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v2 = new Vector3D(x2, y2, z2);

			double expected = x1 * x2 + y1 * y2 + z1 * z2;

			double actual = v2.dot(v1);

			assertEquals(expected, actual, TOLERANCE);
		}
	}

	/**
	 * Tests {@linkplain Vector3D#get(int)}
	 */
	@Test
	public void testGet() {

		final long seed = SEED_PROVIDER.getSeedValue(9);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);

			assertEquals(x, v.get(0), 0);
			assertEquals(y, v.get(1), 0);
			assertEquals(z, v.get(2), 0);

		}
	}

	/**
	 * Tests {@linkplain Vector3D#getX()}
	 */
	@Test
	public void testGetX() {

		final long seed = SEED_PROVIDER.getSeedValue(12);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);

			assertEquals(x, v.getX(), 0);
		}
	}

	/**
	 * Tests {@linkplain Vector3D#getY()}
	 */
	@Test
	public void testGetY() {

		final long seed = SEED_PROVIDER.getSeedValue(10);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);

			assertEquals(y, v.getY(), 0);
		}
	}

	/**
	 * Tests {@linkplain Vector3D#getZ()}
	 */
	@Test
	public void testGetZ() {

		final long seed = SEED_PROVIDER.getSeedValue(11);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);

			assertEquals(z, v.getZ(), 0);
		}
	}

	/**
	 * Tests {@linkplain Vector3D#scale(double)}
	 */
	@Test
	public void testScale() {

		final long seed = SEED_PROVIDER.getSeedValue(13);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);
			double scalar = randomGenerator.nextDouble() * 1000 - 500;

			v = v.scale(scalar);

			assertEquals(x * scalar, v.getX(), 0);
			assertEquals(y * scalar, v.getY(), 0);
			assertEquals(z * scalar, v.getZ(), 0);
		}
	}

	/**
	 * Tests {@linkplain Vector3D#sub(Vector3D)}
	 * 
	 * Tests {@linkplain Vector3D#sub(double, double, double)}
	 */
	@Test
	public void testSub() {

		final long seed = SEED_PROVIDER.getSeedValue(17);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {
			double x1 = randomGenerator.nextDouble() * 1000 - 500;
			double y1 = randomGenerator.nextDouble() * 1000 - 500;
			double z1 = randomGenerator.nextDouble() * 1000 - 500;
			Vector3D v1 = new Vector3D(x1, y1, z1);

			double x2 = randomGenerator.nextDouble() * 1000 - 500;
			double y2 = randomGenerator.nextDouble() * 1000 - 500;
			double z2 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v2 = new Vector3D(x2, y2, z2);

			v1 = v1.sub(v2);

			// Tests {@linkplain Vector3D#sub(MutableVector3D)}
			assertEquals(x1 - x2, v1.getX(), 0);
			assertEquals(y1 - y2, v1.getY(), 0);
			assertEquals(z1 - z2, v1.getZ(), 0);

			v1 = new Vector3D(x1, y1, z1);
			v1 = v1.sub(x2, y2, z2);

			// Tests {@linkplain Vector3D#sub(double, double, double)}
			assertEquals(x1 - x2, v1.getX(), 0);
			assertEquals(y1 - y2, v1.getY(), 0);
			assertEquals(z1 - z2, v1.getZ(), 0);

		}
	}

	/**
	 * Tests {@linkplain Vector3D#isInfinite()}
	 * 
	 */
	@Test
	public void testIsInfinite() {

		final long seed = SEED_PROVIDER.getSeedValue(18);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {
			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);
			assertFalse(v.isInfinite());

			v = new Vector3D(Double.POSITIVE_INFINITY, y, z);
			assertTrue(v.isInfinite());

			v = new Vector3D(Double.NEGATIVE_INFINITY, y, z);
			assertTrue(v.isInfinite());

			v = new Vector3D(x, Double.POSITIVE_INFINITY, z);
			assertTrue(v.isInfinite());

			v = new Vector3D(x, Double.NEGATIVE_INFINITY, z);
			assertTrue(v.isInfinite());

			v = new Vector3D(x, y, Double.POSITIVE_INFINITY);
			assertTrue(v.isInfinite());

			v = new Vector3D(x, y, Double.NEGATIVE_INFINITY);
			assertTrue(v.isInfinite());
		}
	}

	/**
	 * Tests {@linkplain Vector3D#isNaN()}
	 */
	@Test
	public void testIsNaN() {

		final long seed = SEED_PROVIDER.getSeedValue(19);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {
			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;
			Vector3D v = new Vector3D(x, y, z);
			assertFalse(v.isNaN());

			v = new Vector3D(Double.NaN, y, z);
			assertTrue(v.isNaN());

			v = new Vector3D(x, Double.NaN, z);
			assertTrue(v.isNaN());

			v = new Vector3D(x, y, Double.NaN);
			assertTrue(v.isNaN());
		}
	}

	/**
	 * Tests {@linkplain Vector3D#isFinite()}
	 * 
	 */
	@Test
	public void testIsFinite() {

		final long seed = SEED_PROVIDER.getSeedValue(20);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {
			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);
			assertTrue(v.isFinite());

			v = new Vector3D(Double.NaN, y, z);
			assertFalse(v.isFinite());

			v = new Vector3D(Double.NEGATIVE_INFINITY, y, z);
			assertFalse(v.isFinite());

			v = new Vector3D(Double.POSITIVE_INFINITY, y, z);
			assertFalse(v.isFinite());

			v = new Vector3D(x, Double.NaN, z);
			assertFalse(v.isFinite());

			v = new Vector3D(x, Double.NEGATIVE_INFINITY, z);
			assertFalse(v.isFinite());

			v = new Vector3D(x, Double.POSITIVE_INFINITY, z);
			assertFalse(v.isFinite());

			v = new Vector3D(x, y, Double.NaN);
			assertFalse(v.isFinite());

			v = new Vector3D(x, y, Double.NEGATIVE_INFINITY);
			assertFalse(v.isFinite());

			v = new Vector3D(x, y, Double.POSITIVE_INFINITY);
			assertFalse(v.isFinite());

		}
	}

	/**
	 * Tests {@linkplain Vector3D#squareDistanceTo(Vector3D)}
	 */
	@Test
	public void testSquareDistanceTo() {

		final long seed = SEED_PROVIDER.getSeedValue(21);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x1 = randomGenerator.nextDouble() * 1000 - 500;
			double y1 = randomGenerator.nextDouble() * 1000 - 500;
			double z1 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v1 = new Vector3D(x1, y1, z1);

			double x2 = randomGenerator.nextDouble() * 1000 - 500;
			double y2 = randomGenerator.nextDouble() * 1000 - 500;
			double z2 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v2 = new Vector3D(x2, y2, z2);

			double expected = (x1 - x2) * (x1 - x2) + (y1 - y2) * (y1 - y2) + (z1 - z2) * (z1 - z2);

			double actual = v2.squareDistanceTo(v1);

			assertEquals(expected, actual, 0);

		}
	}

	/**
	 * Tests {@linkplain Vector3D#reverse()}
	 */
	@Test
	public void testReverse() {

		final long seed = SEED_PROVIDER.getSeedValue(22);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);
			v = v.reverse();

			assertEquals(-x, v.getX(), 0);
			assertEquals(-y, v.getY(), 0);
			assertEquals(-z, v.getZ(), 0);
		}
	}

	/**
	 * Tests {@linkplain Vector3D#length()}
	 */
	@Test
	public void testLength() {

		final long seed = SEED_PROVIDER.getSeedValue(23);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);
			double expectedLength = FastMath.sqrt(x * x + y * y + z * z);
			double actualLength = v.length();

			assertEquals(expectedLength, actualLength, TOLERANCE);
		}
	}

	/**
	 * Tests {@linkplain Vector3D#squareLength()}
	 */
	@Test
	public void testSquareLength() {

		final long seed = SEED_PROVIDER.getSeedValue(24);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);
			double expectedLength = x * x + y * y + z * z;
			double actualLength = v.squareLength();

			assertEquals(expectedLength, actualLength, 0);
		}
	}

	/**
	 * Tests {@linkplain Vector3D#toArray()}
	 */
	@Test
	public void testToArray() {

		final long seed = SEED_PROVIDER.getSeedValue(25);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);
			double[] array = v.toArray();

			assertEquals(v.getX(), array[0], 0);
			assertEquals(v.getY(), array[1], 0);
			assertEquals(v.getZ(), array[2], 0);
		}
	}

	/**
	 * Tests {@linkplain Vector3D#normalize()}
	 */
	@Test
	public void testNormalize() {

		final long seed = SEED_PROVIDER.getSeedValue(26);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);
			v = v.normalize();

			assertEquals(1, v.length(), TOLERANCE);

		}
	}

	/**
	 * Tests {@linkplain Vector3D#isNormal()}
	 */
	@Test
	public void testisNormal() {

		final long seed = SEED_PROVIDER.getSeedValue(8);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		int activeTestCount = 0;
		for (int i = 0; i < 100; i++) {
			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);

			if (FastMath.abs(v.length() - 1) > Vector3D.NORMAL_LENGTH_TOLERANCE) {
				v = v.normalize();
				assertTrue(v.isNormal());
				activeTestCount++;

				Vector3D u = new Vector3D(v);
				u = u.scale(1 - 2 * Vector3D.NORMAL_LENGTH_TOLERANCE);
				assertFalse(u.isNormal());

				u = new Vector3D(v);
				u = u.scale(1 + 2 * Vector3D.NORMAL_LENGTH_TOLERANCE);
				assertFalse(u.isNormal());
			}
		}
		assertTrue(activeTestCount > 90);
	}

	/**
	 * Tests {@linkplain Vector3D#isPerpendicularTo(Vector3D)}
	 */
	@Test
	public void testIsPerpendicularTo() {

		final long seed = SEED_PROVIDER.getSeedValue(4);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x1 = randomGenerator.nextDouble() * 1000 - 500;
			double y1 = randomGenerator.nextDouble() * 1000 - 500;
			double z1 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v1 = new Vector3D(x1, y1, z1);

			double x2 = randomGenerator.nextDouble() * 1000 - 500;
			double y2 = randomGenerator.nextDouble() * 1000 - 500;
			double z2 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v2 = new Vector3D(x2, y2, z2);

			Vector3D v3 = new Vector3D(v1);
			v3 = v3.rotateToward(new Vector3D(v2), FastMath.toRadians(90));

			assertTrue(v1.isPerpendicularTo(v3));

			v3 = new Vector3D(v1);
			v3 = v3.rotateToward(new Vector3D(v2), FastMath.PI / 2 - 2 * Vector3D.PERPENDICUALR_ANGLE_TOLERANCE);
			assertFalse(v1.isPerpendicularTo(v3));

			v3 = new Vector3D(v1);
			v3 = v3.rotateToward(new Vector3D(v2), FastMath.PI / 2 + 2 * Vector3D.PERPENDICUALR_ANGLE_TOLERANCE);
			assertFalse(v1.isPerpendicularTo(v3));
		}

	}

	/**
	 * Tests {@linkplain Vector3D#equals()}
	 */
	@Test
	public void testEquals() {

		final long seed = SEED_PROVIDER.getSeedValue(27);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v1 = new Vector3D(x, y, z);

			Vector3D v2 = new Vector3D(x, y, z);

			Vector3D v3 = new Vector3D(x, y, z);

			// reflexive
			assertEquals(v1, v1);

			// symetric
			assertEquals(v1, v2);
			assertEquals(v2, v1);

			// transitive
			assertEquals(v1, v2);
			assertEquals(v2, v3);
			assertEquals(v3, v1);

		}
	}

	/**
	 * Tests {@linkplain Vector3D#hashCode()}
	 */
	@Test
	public void testHashCode() {

		final long seed = SEED_PROVIDER.getSeedValue(28);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v1 = new Vector3D(x, y, z);

			Vector3D v2 = new Vector3D(x, y, z);

			assertEquals(v1.hashCode(), v2.hashCode());

		}
	}

	/**
	 * Tests {@linkplain Vector3D#toString()}
	 */
	@Test
	public void testToString() {

		final long seed = SEED_PROVIDER.getSeedValue(16);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			double x = randomGenerator.nextDouble() * 1000 - 500;
			double y = randomGenerator.nextDouble() * 1000 - 500;
			double z = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v = new Vector3D(x, y, z);

			String expected = "Vector3D [x=" + x + ", y=" + y + ", z=" + z + "]";

			String actual = v.toString();

			assertEquals(expected, actual);
		}
	}

	/**
	 * Tests {@linkplain Vector3D#rotateAbout(Vector3D, double)}
	 * 
	 */
	@Test
	public void testRotateAbout() {

		final long seed = SEED_PROVIDER.getSeedValue(15);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			// v1 will be used as a rotator, so we ensure that it has a
			// reasonable length
			Vector3D v1 = new Vector3D();
			while (v1.length() < 0.0000001) {
				double x1 = randomGenerator.nextDouble() * 1000 - 500;
				double y1 = randomGenerator.nextDouble() * 1000 - 500;
				double z1 = randomGenerator.nextDouble() * 1000 - 500;
				v1 = new Vector3D(x1, y1, z1);
			}

			double x2 = randomGenerator.nextDouble() * 1000 - 500;
			double y2 = randomGenerator.nextDouble() * 1000 - 500;
			double z2 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v2 = new Vector3D(x2, y2, z2);

			double theta = randomGenerator.nextDouble() * 2 * FastMath.PI;

			Vector3D v = new Vector3D(v2);

			v = v.rotateAbout(v1, theta);

			// v2 under rotation should have its length preserved
			assertEquals(v2.length(), v.length(), TOLERANCE);

			// v2 under rotation should have its angle to v1 preserved
			assertEquals(v2.angle(v1), v.angle(v1), TOLERANCE);

			// v2 when rotated back should return to its original position
			v = v.rotateAbout(v1, -theta);
			assertEquals(v2.getX(), v.getX(), TOLERANCE);
			assertEquals(v2.getY(), v.getY(), TOLERANCE);
			assertEquals(v2.getZ(), v.getZ(), TOLERANCE);

		}
	}

	/**
	 * 
	 * Tests {@linkplain Vector3D#rotateToward(Vector3D, double)}
	 */
	@Test
	public void testRotateToward() {

		final long seed = SEED_PROVIDER.getSeedValue(14);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		for (int i = 0; i < 100; i++) {

			// v1 will be used as a rotator, so we ensure that it has a
			// reasonable length
			Vector3D v1 = new Vector3D();
			while (v1.length() < 0.0000001) {
				double x1 = randomGenerator.nextDouble() * 1000 - 500;
				double y1 = randomGenerator.nextDouble() * 1000 - 500;
				double z1 = randomGenerator.nextDouble() * 1000 - 500;
				v1 = new Vector3D(x1, y1, z1);
			}

			double x2 = randomGenerator.nextDouble() * 1000 - 500;
			double y2 = randomGenerator.nextDouble() * 1000 - 500;
			double z2 = randomGenerator.nextDouble() * 1000 - 500;

			Vector3D v2 = new Vector3D(x2, y2, z2);

			double theta = randomGenerator.nextDouble() * 2 * FastMath.PI;

			Vector3D v = new Vector3D(v2);

			v = v.rotateToward(v1, theta);
			double angle = v2.angle(v1);

			// v2 under rotation should have its length preserved
			assertEquals(v2.length(), v.length(), TOLERANCE);

			// v2 under rotation should have its angle to v1 changed by theta
			double expectedAngle = theta - angle;
			while (expectedAngle < 0) {
				expectedAngle += FastMath.PI * 2;
			}
			while (expectedAngle > 2 * FastMath.PI) {
				expectedAngle -= 2 * FastMath.PI;
			}
			while (expectedAngle > FastMath.PI) {
				expectedAngle = 2 * FastMath.PI - expectedAngle;
			}

			double actualAngle = v.angle(v1);

			assertEquals(expectedAngle, actualAngle, TOLERANCE);

			// v2 when rotated back should return to its original position
			Vector3D a = new Vector3D(v2);
			a = a.cross(v1);

			Vector3D b = new Vector3D(v);
			b = b.cross(v1);

			if (a.dot(b) > 0) {
				v = v.rotateToward(v1, -theta);
			} else {
				v = v.rotateToward(v1, theta);
			}

			assertEquals(v2.getX(), v.getX(), TOLERANCE);
			assertEquals(v2.getY(), v.getY(), TOLERANCE);
			assertEquals(v2.getZ(), v.getZ(), TOLERANCE);

		}
	}

}
