package gcm.automated;

import static gcm.automated.support.EnvironmentSupport.addObservationContainer;
import static gcm.automated.support.EnvironmentSupport.addStandardComponentsAndTypes;
import static gcm.automated.support.EnvironmentSupport.addStandardPeople;
import static gcm.automated.support.EnvironmentSupport.addStandardPropertyDefinitions;
import static gcm.automated.support.EnvironmentSupport.addStandardTrackingAndScenarioId;
import static gcm.automated.support.EnvironmentSupport.addTaskPlanContainer;
import static gcm.automated.support.EnvironmentSupport.assertAllPlansExecuted;
import static gcm.automated.support.EnvironmentSupport.generatePropertyValue;
import static gcm.automated.support.EnvironmentSupport.getRandomGenerator;
import static gcm.automated.support.EnvironmentSupport.getReplication;
import static gcm.automated.support.ExceptionAssertion.assertModelException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import org.apache.commons.math3.random.RandomGenerator;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import gcm.automated.support.EnvironmentSupport;
import gcm.automated.support.EnvironmentSupport.PropertyAssignmentPolicy;
import gcm.automated.support.ObservationContainer;
import gcm.automated.support.SeedProvider;
import gcm.automated.support.TaskPlanContainer;
import gcm.automated.support.TestCompartmentId;
import gcm.automated.support.TestGlobalComponentId;
import gcm.automated.support.TestGlobalPropertyId;
import gcm.automated.support.TestMaterialsProducerId;
import gcm.automated.support.TestMaterialsProducerPropertyId;
import gcm.automated.support.TestPersonPropertyId;
import gcm.automated.support.TestRegionId;
import gcm.automated.support.TestResourceId;
import gcm.replication.Replication;
import gcm.scenario.CompartmentId;
import gcm.scenario.GlobalPropertyId;
import gcm.scenario.MaterialsProducerId;
import gcm.scenario.MaterialsProducerPropertyId;
import gcm.scenario.PersonId;
import gcm.scenario.PersonPropertyId;
import gcm.scenario.PropertyDefinition;
import gcm.scenario.RegionId;
import gcm.scenario.ResourceId;
import gcm.scenario.Scenario;
import gcm.scenario.ScenarioBuilder;
import gcm.scenario.UnstructuredScenarioBuilder;
import gcm.simulation.EnvironmentImpl;
import gcm.simulation.ObservationType;
import gcm.simulation.Simulation;
import gcm.simulation.SimulationErrorType;
import gcm.util.MultiKey;
import gcm.util.annotations.UnitTest;
import gcm.util.annotations.UnitTestMethod;

@UnitTest(target = EnvironmentImpl.class)

public class AT_EnvironmentImpl_13 {

	private static SeedProvider SEED_PROVIDER;

	@BeforeClass
	public static void beforeClass() {
		SEED_PROVIDER = new SeedProvider(EnvironmentSupport.getMetaSeed(13));
	}

	/**
	 * Internal test(not part of public tests) to show that there are no large
	 * gaps in the seed cases generated by the SeedProvider.
	 */
	@AfterClass
	public static void afterClass() {
//		 System.out.println(AT_EnvironmentImpl_13.class.getSimpleName() + " "
//		 + SEED_PROVIDER.generateUnusedSeedReport());
	}

	/**
	 * Tests {@link EnvironmentImpl#observeGlobalPersonArrival(boolean)}
	 *
	 */
	@Test
	@UnitTestMethod(name = "observeGlobalPersonArrival", args = {boolean.class})
	public void testObserveGlobalPersonArrival() {
		/*
		 * We test for the post conditions by first having the components
		 * execute a series time-separated plans and then examining the
		 * observations recorded by each component.
		 *
		 * Actions
		 *
		 * Time 1 : Compartment 1 starts observation
		 *
		 * Time 2 : Region 1 starts observation
		 *
		 * Time 3 : Compartment 2 starts observation
		 *
		 * Time 4 : Compartment 3 starts observation
		 *
		 * Time 5 : Global Component 1 starts observation and then adds a person
		 *
		 * Time 6 : Compartment 1 stops observation
		 *
		 * Time 7 : Global Component 1 adds a person
		 *
		 * Expected observations
		 *
		 * Compartment 1: first person --> demonstrates Post Conditions 1 and 3
		 *
		 * Compartment 3: first and second person --> demonstrates Post
		 * Conditions 1 and 2
		 *
		 * Region 1: first and second person --> demonstrates Post Conditions 1
		 *
		 * Global Component 1: no observations --> demonstrates Post Condition 4
		 *
		 * All others: no observations --> demonstrates Post Condition 2
		 */
		final long seed = SEED_PROVIDER.getSeedValue(0);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		ScenarioBuilder scenarioBuilder = new UnstructuredScenarioBuilder();
		addStandardTrackingAndScenarioId(scenarioBuilder, randomGenerator);
		addStandardComponentsAndTypes(scenarioBuilder);
		addStandardPeople(scenarioBuilder, 10);
		ObservationContainer observationContainer = addObservationContainer(scenarioBuilder);
		addStandardPropertyDefinitions(scenarioBuilder, PropertyAssignmentPolicy.RANDOM, randomGenerator);

		TaskPlanContainer taskPlanContainer = addTaskPlanContainer(scenarioBuilder);

		Scenario scenario = scenarioBuilder.build();

		Replication replication = getReplication(randomGenerator);

		int testTime = 1;

		/*
		 * Time 1 : Compartment 1 starts observation
		 */

		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.observeGlobalPersonArrival(true);
		});

		/*
		 * Time 2 : Region 1 starts observation
		 */

		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.observeGlobalPersonArrival(true);
		});

		/*
		 * Time 3 : Compartment 2 starts observation
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_2, testTime++, (environment) -> {
			environment.observeGlobalPersonArrival(false);
		});

		/*
		 * Time 4 : Compartment 3 starts observation
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_3, testTime++, (environment) -> {
			environment.observeGlobalPersonArrival(true);
		});

		/*
		 * Time 5 : Global Component 1 starts observation and then adds a person
		 */
		final double firstObservationTime = testTime;
		final PersonId firstPersonId = new PersonId(scenario.getPeopleIds().size());
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.observeGlobalPersonArrival(true);
			environment.addPerson(TestRegionId.REGION_1, TestCompartmentId.COMPARTMENT_3);
		});

		/*
		 * Time 6 : Compartment 1 stops observation
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.observeGlobalPersonArrival(false);
		});

		/*
		 * Time 7 : Global Component 1 adds a person
		 */
		final double secondObservationTime = testTime;
		final PersonId secondPersonId = new PersonId(firstPersonId.getValue() + 1);
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.addPerson(TestRegionId.REGION_2, TestCompartmentId.COMPARTMENT_1);
		});

		Simulation simulation = new Simulation();
		simulation.setReplication(replication);
		simulation.setScenario(scenario);
		simulation.execute();

		assertAllPlansExecuted(taskPlanContainer);

		final Set<MultiKey> expectedObservations = new LinkedHashSet<>();

		/*
		 * Compartment 1: first person --> demonstrates Post Conditions 1 and 3
		 */

		expectedObservations.add(new MultiKey(firstObservationTime, TestCompartmentId.COMPARTMENT_1, ObservationType.GLOBAL_PERSON_ARRIVAL, firstPersonId));

		/*
		 * Compartment 3: first and second person --> demonstrates Post
		 * Conditions 1 and 2
		 */
		expectedObservations.add(new MultiKey(firstObservationTime, TestCompartmentId.COMPARTMENT_3, ObservationType.GLOBAL_PERSON_ARRIVAL, firstPersonId));
		expectedObservations.add(new MultiKey(secondObservationTime, TestCompartmentId.COMPARTMENT_3, ObservationType.GLOBAL_PERSON_ARRIVAL, secondPersonId));

		/*
		 * Region 1: first and second person --> demonstrates Post Conditions 1
		 */

		expectedObservations.add(new MultiKey(firstObservationTime, TestRegionId.REGION_1, ObservationType.GLOBAL_PERSON_ARRIVAL, firstPersonId));
		expectedObservations.add(new MultiKey(secondObservationTime, TestRegionId.REGION_1, ObservationType.GLOBAL_PERSON_ARRIVAL, secondPersonId));

		/*
		 * Global Component 1: no observations --> demonstrates Post Condition 4
		 */

		/*
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		final Set<MultiKey> actualObservations = observationContainer.getObservations();

		assertEquals(expectedObservations, actualObservations);

	}

	/**
	 * Tests {@link EnvironmentImpl#observeGlobalPersonDeparture(boolean)}
	 *
	 */
	@Test
	@UnitTestMethod(name = "observeGlobalPersonDeparture", args = {boolean.class})
	public void testObserveGlobalPersonDeparture() {
		/*
		 * We test for the post conditions by first having the components
		 * execute a series time-separated plans and then examining the
		 * observations recorded by each component.
		 *
		 * Actions
		 *
		 * Time 1 : Global Component 1 starts observation
		 *
		 * Time 2 : Compartment 2 starts observation
		 *
		 * Time 3 : Compartment 2 removes a first person
		 *
		 * Time 4 : Global Component 1 stops observation
		 *
		 * Time 5 : Region 1 starts observation
		 *
		 * Time 6 : Compartment 2 removes a second person
		 *
		 * Expected observations
		 *
		 * Global Component 1: first person removal --> demonstrates Post
		 * Conditions 1 and 3
		 *
		 * Compartment 2: no observations demonstrates Post Condition 4
		 *
		 * Region 1: second person removal --> demonstrates Post Conditions 1
		 * and 2
		 *
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		final long seed = SEED_PROVIDER.getSeedValue(1);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		ScenarioBuilder scenarioBuilder = new UnstructuredScenarioBuilder();
		addStandardTrackingAndScenarioId(scenarioBuilder, randomGenerator);
		addStandardComponentsAndTypes(scenarioBuilder);
		addStandardPeople(scenarioBuilder, 10);
		ObservationContainer observationContainer = addObservationContainer(scenarioBuilder);
		addStandardPropertyDefinitions(scenarioBuilder, PropertyAssignmentPolicy.RANDOM, randomGenerator);

		TaskPlanContainer taskPlanContainer = addTaskPlanContainer(scenarioBuilder);

		Scenario scenario = scenarioBuilder.build();

		Replication replication = getReplication(randomGenerator);

		int testTime = 1;

		/*
		 * Get the two people to remove
		 */
		final List<PersonId> peopleInCompartment2 = new ArrayList<>();
		for (final PersonId personId : scenario.getPeopleIds()) {
			final CompartmentId personCompartment = scenario.getPersonCompartment(personId);
			if (personCompartment.equals(TestCompartmentId.COMPARTMENT_2)) {
				peopleInCompartment2.add(personId);
			}
		}
		assertTrue(peopleInCompartment2.size() >= 2);

		final PersonId firstPerson = peopleInCompartment2.get(0);
		final PersonId secondPerson = peopleInCompartment2.get(1);

		/*
		 * Time 1 : Global Component 1 starts observation
		 */

		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.observeGlobalPersonDeparture(true);
		});

		/*
		 * Time 2 : Compartment 2 starts observation
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_2, testTime++, (environment) -> {
			environment.observeGlobalPersonDeparture(true);
		});

		/*
		 * Time 3 : Compartment 2 removes a first person
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_2, testTime++, (environment) -> {
			environment.removePerson(firstPerson);
		});

		/*
		 * Time 4 : Global Component 1 stops observation
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.observeGlobalPersonDeparture(false);
		});

		/*
		 * Time 5 : Region 1 starts observation
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.observeGlobalPersonDeparture(true);
		});

		/*
		 * Time 6 : Compartment 2 removes a second person
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_2, testTime++, (environment) -> {
			environment.removePerson(secondPerson);
		});

		Simulation simulation = new Simulation();
		simulation.setReplication(replication);
		simulation.setScenario(scenario);
		simulation.execute();

		assertAllPlansExecuted(taskPlanContainer);

		final Set<MultiKey> expectedObservations = new LinkedHashSet<>();

		/*
		 * Expected observations
		 *
		 * Global Component 1: first person removal --> demonstrates Post
		 * Conditions 1 and 3
		 */
		expectedObservations.add(new MultiKey(3.0, TestGlobalComponentId.GLOBAL_COMPONENT_1, ObservationType.GLOBAL_PERSON_DEPARTURE, firstPerson));

		/*
		 * Compartment 2: no observations demonstrates Post Condition 4
		 */

		/*
		 * Region 1: second person removal --> demonstrates Post Conditions 1
		 * and 2
		 */
		expectedObservations.add(new MultiKey(6.0, TestRegionId.REGION_1, ObservationType.GLOBAL_PERSON_DEPARTURE, secondPerson));

		/*
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		final Set<MultiKey> actualObservations = observationContainer.getObservations();

		assertEquals(expectedObservations, actualObservations);

	}

	/**
	 * Tests
	 * {@link EnvironmentImpl#observeGlobalPersonPropertyChange(boolean, PersonPropertyId)}
	 *
	 */
	@Test
	@UnitTestMethod(name = "observeGlobalPersonPropertyChange", args = {boolean.class,PersonPropertyId.class})
	public void testObserveGlobalPersonPropertyChange() {
		/*
		 * We test for the post conditions by first having the components
		 * execute a series time-separated plans and then examining the
		 * observations recorded by each component. Precondition tests are added
		 * at the end.
		 *
		 * Actions
		 *
		 * Time 1 : Compartment 1 starts observation of Person Property P
		 *
		 * Time 2 : Compartment 2 starts observation of Person Property P
		 *
		 * Time 3 : Compartment 2 changes a person's property value
		 *
		 * Time 4 : Compartment 1 stops observation of Person Property P
		 *
		 * Time 5 : Region 1 starts observation of Person Property P
		 *
		 * Time 6 : Compartment 2 changes a person's property
		 *
		 * Expected observations
		 *
		 * Compartment 1: first property change --> demonstrates Post Conditions
		 * 1 and 3
		 *
		 * Compartment 2: no observations demonstrates Post Condition 4
		 *
		 * Region 1: second property change --> demonstrates Post Conditions 1
		 * and 2
		 *
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		final long seed = SEED_PROVIDER.getSeedValue(2);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		ScenarioBuilder scenarioBuilder = new UnstructuredScenarioBuilder();
		addStandardTrackingAndScenarioId(scenarioBuilder, randomGenerator);
		addStandardComponentsAndTypes(scenarioBuilder);
		addStandardPeople(scenarioBuilder, 10);
		addStandardPropertyDefinitions(scenarioBuilder, PropertyAssignmentPolicy.TRUE, randomGenerator);

		ObservationContainer observationContainer = addObservationContainer(scenarioBuilder);

		TaskPlanContainer taskPlanContainer = addTaskPlanContainer(scenarioBuilder);

		Scenario scenario = scenarioBuilder.build();

		Replication replication = getReplication(randomGenerator);

		int testTime = 1;

		/*
		 * Establish a non-boolean property so that we can have two distinct
		 * values different from the current value.
		 */
		TestPersonPropertyId candidatePropertyId = null;
		for (final TestPersonPropertyId personPropertyId : TestPersonPropertyId.values()) {
			final PropertyDefinition propertyDefinition = scenario.getPersonPropertyDefinition(personPropertyId);
			if (propertyDefinition.getType() != Boolean.class) {
				candidatePropertyId = personPropertyId;
				break;
			}

		}
		assertNotNull(candidatePropertyId);
		final TestPersonPropertyId selectedPersonPropertyId = candidatePropertyId;

		final PropertyDefinition propertyDefinition = scenario.getPersonPropertyDefinition(selectedPersonPropertyId);
		assertTrue(propertyDefinition.getDefaultValue().isPresent());
		final Object currentPropertyValue = propertyDefinition.getDefaultValue().get();
		Object propertyValue1 = null;
		while (currentPropertyValue.equals(propertyValue1) || (propertyValue1 == null)) {
			propertyValue1 = generatePropertyValue(propertyDefinition, randomGenerator);
		}
		assertNotNull(propertyValue1);
		assertFalse(propertyValue1.equals(currentPropertyValue));
		Object propertyValue2 = null;
		while (currentPropertyValue.equals(propertyValue2) || propertyValue1.equals(propertyValue2) || (propertyValue2 == null)) {
			propertyValue2 = generatePropertyValue(propertyDefinition, randomGenerator);
		}
		assertNotNull(propertyValue2);
		assertFalse(propertyValue2.equals(currentPropertyValue));
		assertFalse(propertyValue2.equals(propertyValue1));

		final Object firstPropertyValue = propertyValue1;
		final Object secondPropertyValue = propertyValue2;

		final List<PersonId> peopleInCompartment2 = new ArrayList<>();
		for (final PersonId personId : scenario.getPeopleIds()) {
			final CompartmentId personCompartment = scenario.getPersonCompartment(personId);
			if (personCompartment.equals(TestCompartmentId.COMPARTMENT_2)) {
				peopleInCompartment2.add(personId);
			}
		}
		assertTrue(peopleInCompartment2.size() >= 1);
		final PersonId selectedPersonId = peopleInCompartment2.get(0);

		/*
		 * Time 1 : Compartment 1 starts observation of Person Property P
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.observeGlobalPersonPropertyChange(true, selectedPersonPropertyId);
		});

		/*
		 * Time 2 : Compartment 2 starts observation of Person Property P
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_2, testTime++, (environment) -> {

			environment.observeGlobalPersonPropertyChange(true, selectedPersonPropertyId);
		});
		/*
		 * Time 3 : Compartment 2 changes a person's property value
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_2, testTime++, (environment) -> {

			environment.setPersonPropertyValue(selectedPersonId, selectedPersonPropertyId, firstPropertyValue);
		});

		/*
		 * Time 4 : Compartment 1 stops observation of Person property P
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.observeGlobalPersonPropertyChange(false, selectedPersonPropertyId);
		});

		/*
		 * Time 5 : Region 1 starts observation of Person property P
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.observeGlobalPersonPropertyChange(true, selectedPersonPropertyId);
		});

		/*
		 * Time 6 : Compartment 2 changes a person's property
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_2, testTime++, (environment) -> {
			environment.setPersonPropertyValue(selectedPersonId, selectedPersonPropertyId, secondPropertyValue);
		});

		/*
		 * Precondition tests
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			// if the property id is null
			assertModelException(() -> environment.observeGlobalPersonPropertyChange(true, null), SimulationErrorType.NULL_PERSON_PROPERTY_ID);
			// if the property is unknown
			assertModelException(() -> environment.observeGlobalPersonPropertyChange(true, TestPersonPropertyId.getUnknownPersonPropertyId()), SimulationErrorType.UNKNOWN_PERSON_PROPERTY_ID);
		});

		Simulation simulation = new Simulation();
		simulation.setReplication(replication);
		simulation.setScenario(scenario);
		simulation.execute();

		assertAllPlansExecuted(taskPlanContainer);

		final Set<MultiKey> expectedObservations = new LinkedHashSet<>();

		/*
		 * Expected observations
		 *
		 * Compartment 1: first property change --> demonstrates Post Conditions
		 * 1 and 3
		 */

		expectedObservations.add(new MultiKey(3.0, TestCompartmentId.COMPARTMENT_1, ObservationType.PERSON_PROPERTY, selectedPersonId, selectedPersonPropertyId, firstPropertyValue));

		/*
		 * Compartment 2: no observations demonstrates Post Condition 4
		 */

		/*
		 * Region 1: second property change --> demonstrates Post Conditions 1
		 * and 2
		 */
		expectedObservations.add(new MultiKey(6.0, TestRegionId.REGION_1, ObservationType.PERSON_PROPERTY, selectedPersonId, selectedPersonPropertyId, secondPropertyValue));
		/*
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		final Set<MultiKey> actualObservations = observationContainer.getObservations();

		assertEquals(expectedObservations, actualObservations);

	}

	/**
	 * Tests
	 * {@link EnvironmentImpl#observeGlobalPersonResourceChange(boolean, ResourceId)}
	 *
	 */
	@Test
	@UnitTestMethod(name = "observeGlobalPersonResourceChange", args = {boolean.class,ResourceId.class})
	public void testObserveGlobalPersonResourceChange() {
		/*
		 * We test for the post conditions by first having the components
		 * execute a series time-separated plans and then examining the
		 * observations recorded by each component. Precondition tests are added
		 * at the end.
		 *
		 * Actions
		 *
		 * Time 1 : Compartment 1 starts observation of person's Resource Level.
		 * Person will be in Compartment 1 and Region 1.
		 *
		 * Time 2 : Region 1 starts observation of person's Resource Level
		 *
		 * Time 3 : Compartment 2 starts observation of person's Resource Level
		 *
		 * Time 4 : Region 1 changes person's Resource Level by transfer to
		 * person from Region 1
		 *
		 * Time 5 : Global Component 1 starts observation of person's Resource
		 * Level
		 *
		 * Time 6 : Compartment 2 stops observation of person's Resource Level
		 *
		 * Time 7 : Region 1 changes person's resource level by transfer from
		 * person to Region 1
		 *
		 * Time 8 : Compartment 1 changes person's Resource Level by removing
		 * resource from person
		 *
		 * Expected observations
		 *
		 * Compartment 1: first and second resource changes --> demonstrates
		 * Post Conditions 1 and 4
		 *
		 * Compartment 2: first resource change --> demonstrates Post Condition
		 * 1 and 3
		 *
		 * Region 1: third property changes --> demonstrates Post Conditions 1
		 * and 4
		 *
		 * Global Component 1: second and third property changes -->
		 * demonstrates Post Conditions 1 and 2
		 *
		 * All others: no observations --> demonstrates Post Condition 2
		 */
		final long seed = SEED_PROVIDER.getSeedValue(3);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		ScenarioBuilder scenarioBuilder = new UnstructuredScenarioBuilder();
		addStandardTrackingAndScenarioId(scenarioBuilder, randomGenerator);
		addStandardComponentsAndTypes(scenarioBuilder);
		addStandardPeople(scenarioBuilder, 10);
		addStandardPropertyDefinitions(scenarioBuilder, PropertyAssignmentPolicy.TRUE, randomGenerator);

		ObservationContainer observationContainer = addObservationContainer(scenarioBuilder);

		TaskPlanContainer taskPlanContainer = addTaskPlanContainer(scenarioBuilder);

		Scenario scenario = scenarioBuilder.build();

		Replication replication = getReplication(randomGenerator);

		int testTime = 1;

		/*
		 * Select a resource
		 */
		final TestResourceId selectedResourceId = TestResourceId.getRandomResourceId(randomGenerator);

		/*
		 * Select a person from Compartment 1, Region 1
		 */
		final List<PersonId> peopleInCompartment1AndRegion1 = new ArrayList<>();
		for (final PersonId personId : scenario.getPeopleIds()) {
			final CompartmentId personCompartment = scenario.getPersonCompartment(personId);
			if (personCompartment.equals(TestCompartmentId.COMPARTMENT_1)) {
				final RegionId personRegion = scenario.getPersonRegion(personId);
				if (personRegion.equals(TestRegionId.REGION_1)) {
					peopleInCompartment1AndRegion1.add(personId);
				}
			}
		}
		assertTrue(peopleInCompartment1AndRegion1.size() >= 1);
		final int personIndex = randomGenerator.nextInt(peopleInCompartment1AndRegion1.size());
		final PersonId selectedPersonId = peopleInCompartment1AndRegion1.get(personIndex);

		/*
		 * select amounts to move and calculate expected resulting resource
		 * levels for the selected person and resource
		 */
		final long firstAmount = 1000;
		final long secondAmount = 300;
		final long thirdAmount = 400;

		final long expectedFirstLevel = firstAmount;
		final long expectedSecondLevel = firstAmount - secondAmount;
		final long expectedThirdLevel = expectedSecondLevel - thirdAmount;

		/*
		 * Time 1 : Compartment 1 starts observation of person's Resource Level.
		 * Person will be in Compartment 1 and Region 1.
		 */

		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.observeGlobalPersonResourceChange(true, selectedResourceId);
		});

		/*
		 * Time 2 : Region 1 starts observation of person's Resource Level
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.observeGlobalPersonResourceChange(true, selectedResourceId);
		});

		/*
		 * Time 3 : Compartment 2 starts observation of person's Resource Level
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_2, testTime++, (environment) -> {
			environment.observeGlobalPersonResourceChange(true, selectedResourceId);
		});

		/*
		 * Time 4 :Region 1 changes person's Resource Level by transfer to
		 * person from Region 1
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.addResourceToRegion(selectedResourceId, TestRegionId.REGION_1, firstAmount);
			environment.transferResourceToPerson(selectedResourceId, selectedPersonId, firstAmount);
		});

		/*
		 * Time 5 : Global Component 1 starts observation of person's Resource
		 * Level
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.observeGlobalPersonResourceChange(true, selectedResourceId);
		});

		/*
		 * Time 6 : Compartment 2 stops observation of person's Resource Level
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_2, testTime++, (environment) -> {
			environment.observeGlobalPersonResourceChange(false, selectedResourceId);
		});

		/*
		 * Time 7 : Region 1 changes person's resource level by transfer from
		 * person to Region 1
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.transferResourceFromPerson(selectedResourceId, selectedPersonId, secondAmount);
		});
		/*
		 * Time 8 : Compartment 1 changes person's Resource Level by removing
		 * resource from person
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.removeResourceFromPerson(selectedResourceId, selectedPersonId, thirdAmount);
		});

		/*
		 * Precondition tests
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			// if the resource id is null
			assertModelException(() -> environment.observeGlobalPersonResourceChange(true, null), SimulationErrorType.NULL_RESOURCE_ID);
			// if the resource is unknown
			assertModelException(() -> environment.observeGlobalPersonResourceChange(true, TestResourceId.getUnknownResourceId()), SimulationErrorType.UNKNOWN_RESOURCE_ID);

		});

		Simulation simulation = new Simulation();
		simulation.setReplication(replication);
		simulation.setScenario(scenario);
		simulation.execute();

		assertAllPlansExecuted(taskPlanContainer);

		final Set<MultiKey> expectedObservations = new LinkedHashSet<>();

		/*
		 * Compartment 1: first and second resource changes --> demonstrates
		 * Post Conditions 1 and 4
		 */
		expectedObservations.add(new MultiKey(4.0, TestCompartmentId.COMPARTMENT_1, ObservationType.PERSON_RESOURCE, selectedPersonId, selectedResourceId, expectedFirstLevel));

		expectedObservations.add(new MultiKey(7.0, TestCompartmentId.COMPARTMENT_1, ObservationType.PERSON_RESOURCE, selectedPersonId, selectedResourceId, expectedSecondLevel));

		/*
		 * Compartment 2: first resource change --> demonstrates Post Condition
		 * 1 and 3
		 */

		expectedObservations.add(new MultiKey(4.0, TestCompartmentId.COMPARTMENT_2, ObservationType.PERSON_RESOURCE, selectedPersonId, selectedResourceId, expectedFirstLevel));

		/*
		 * Region 1: third property changes --> demonstrates Post Conditions 1
		 * and 4
		 */

		expectedObservations.add(new MultiKey(8.0, TestRegionId.REGION_1, ObservationType.PERSON_RESOURCE, selectedPersonId, selectedResourceId, expectedThirdLevel));

		/*
		 * Global Component 1: second and third property changes -->
		 * demonstrates Post Conditions 1 and 2
		 */
		expectedObservations.add(new MultiKey(7.0, TestGlobalComponentId.GLOBAL_COMPONENT_1, ObservationType.PERSON_RESOURCE, selectedPersonId, selectedResourceId, expectedSecondLevel));

		expectedObservations.add(new MultiKey(8.0, TestGlobalComponentId.GLOBAL_COMPONENT_1, ObservationType.PERSON_RESOURCE, selectedPersonId, selectedResourceId, expectedThirdLevel));

		/*
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		final Set<MultiKey> actualObservations = observationContainer.getObservations();

		assertEquals(expectedObservations, actualObservations);

	}

	/**
	 * Tests
	 * {@link EnvironmentImpl#observeGlobalPropertyChange(boolean, GlobalPropertyId)}
	 *
	 */
	@Test
	@UnitTestMethod(name = "observeGlobalPropertyChange", args = {boolean.class,GlobalPropertyId.class})
	public void testObserveGlobalPropertyChange() {
		/*
		 * We test for the post conditions by first having the components
		 * execute a series time-separated plans and then examining the
		 * observations recorded by each component. Precondition tests are added
		 * at the end.
		 *
		 * Actions
		 *
		 * Time 1 : Compartment 1 starts observation of Global Property P
		 *
		 * Time 2 : Global Component 1 starts observation of Global Property P
		 *
		 * Time 3 : Global Component 1 changes Global Property P value
		 *
		 * Time 4 : Compartment 1 stops observation of Global Property P
		 *
		 * Time 5 : Region 1 starts observation of Global Property P
		 *
		 * Time 6 : Global Component 2 changes Global Property P value
		 *
		 * Expected observations
		 *
		 * Compartment 1: first property change --> demonstrates Post Conditions
		 * 1 and 3
		 *
		 * Global Component 1: second property change demonstrates Post
		 * Conditions 1 and 4
		 *
		 * Region 1: second property change --> demonstrates Post Conditions 1
		 * and 2
		 *
		 * All others: no observations --> demonstrates Post Condition 2
		 */
		final long seed = SEED_PROVIDER.getSeedValue(4);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		ScenarioBuilder scenarioBuilder = new UnstructuredScenarioBuilder();
		addStandardTrackingAndScenarioId(scenarioBuilder, randomGenerator);
		addStandardComponentsAndTypes(scenarioBuilder);
		addStandardPeople(scenarioBuilder, 10);
		addStandardPropertyDefinitions(scenarioBuilder, PropertyAssignmentPolicy.TRUE, randomGenerator);

		ObservationContainer observationContainer = addObservationContainer(scenarioBuilder);

		TaskPlanContainer taskPlanContainer = addTaskPlanContainer(scenarioBuilder);

		Scenario scenario = scenarioBuilder.build();

		Replication replication = getReplication(randomGenerator);

		int testTime = 1;

		/*
		 * Establish a non-boolean property so that we can have two distinct
		 * values different from the current value.
		 */
		TestGlobalPropertyId candidatePropertyId = null;
		for (final TestGlobalPropertyId globalPropertyId : TestGlobalPropertyId.values()) {
			final PropertyDefinition propertyDefinition = scenario.getGlobalPropertyDefinition(globalPropertyId);
			if (propertyDefinition.getType() != Boolean.class) {
				candidatePropertyId = globalPropertyId;
				break;
			}

		}
		assertNotNull(candidatePropertyId);
		final TestGlobalPropertyId selectedGlobalPropertyId = candidatePropertyId;
		final PropertyDefinition propertyDefinition = scenario.getGlobalPropertyDefinition(selectedGlobalPropertyId);
		assertTrue(propertyDefinition.getDefaultValue().isPresent());
		final Object currentPropertyValue = propertyDefinition.getDefaultValue().get();
		Object propertyValue1 = null;
		while (currentPropertyValue.equals(propertyValue1) || (propertyValue1 == null)) {
			propertyValue1 = generatePropertyValue(propertyDefinition, randomGenerator);
		}
		assertNotNull(propertyValue1);
		assertFalse(propertyValue1.equals(currentPropertyValue));
		Object propertyValue2 = null;
		while (currentPropertyValue.equals(propertyValue2) || propertyValue1.equals(propertyValue2) || (propertyValue2 == null)) {
			propertyValue2 = generatePropertyValue(propertyDefinition, randomGenerator);
		}
		assertNotNull(propertyValue2);
		assertFalse(propertyValue2.equals(currentPropertyValue));
		assertFalse(propertyValue2.equals(propertyValue1));

		final Object firstPropertyValue = propertyValue1;
		final Object secondPropertyValue = propertyValue2;

		/*
		 * Time 1 : Compartment 1 starts observation of Global Property P
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.observeGlobalPropertyChange(true, selectedGlobalPropertyId);
		});

		/*
		 * Time 2 : Global Component 1 starts observation of Global Property P
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.observeGlobalPropertyChange(true, selectedGlobalPropertyId);
		});

		/*
		 * Time 3 : Global Component 1 changes Global Property P value
		 */

		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.setGlobalPropertyValue(selectedGlobalPropertyId, firstPropertyValue);
		});

		/*
		 * Time 4 : Compartment 1 stops observation of Global Property P
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.observeGlobalPropertyChange(false, selectedGlobalPropertyId);
		});

		/*
		 * Time 5 : Region 1 starts observation of Global Property P
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.observeGlobalPropertyChange(true, selectedGlobalPropertyId);
		});

		/*
		 * Time 6 : Global Component 2 changes Global Property P value
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_2, testTime++, (environment) -> {
			environment.setGlobalPropertyValue(selectedGlobalPropertyId, secondPropertyValue);
		});

		/*
		 * Precondition tests
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			// if the property id is null
			assertModelException(() -> environment.observeGlobalPropertyChange(true, null), SimulationErrorType.NULL_GLOBAL_PROPERTY_ID);
			// if the property id is unknown
			assertModelException(() -> environment.observeGlobalPropertyChange(true, TestGlobalPropertyId.getUnknownGlobalPropertyId()), SimulationErrorType.UNKNOWN_GLOBAL_PROPERTY_ID);
		});

		Simulation simulation = new Simulation();
		simulation.setReplication(replication);
		simulation.setScenario(scenario);
		simulation.execute();

		assertAllPlansExecuted(taskPlanContainer);

		final Set<MultiKey> expectedObservations = new LinkedHashSet<>();

		/*
		 * Compartment 1: first property change --> demonstrates Post Conditions
		 * 1 and 3
		 */

		expectedObservations.add(new MultiKey(3.0, TestCompartmentId.COMPARTMENT_1, ObservationType.GLOBAL_PROPERTY, selectedGlobalPropertyId, firstPropertyValue));

		/*
		 * Global Component 1: second property change demonstrates Post
		 * Conditions 1 and 4
		 */

		expectedObservations.add(new MultiKey(6.0, TestGlobalComponentId.GLOBAL_COMPONENT_1, ObservationType.GLOBAL_PROPERTY, selectedGlobalPropertyId, secondPropertyValue));

		/*
		 * Region 1: second property change --> demonstrates Post Conditions 1
		 * and 2
		 */
		expectedObservations.add(new MultiKey(6.0, TestRegionId.REGION_1, ObservationType.GLOBAL_PROPERTY, selectedGlobalPropertyId, secondPropertyValue));

		/*
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		/*
		 * All others: no observations --> demonstrates Post Condition 2
		 */
		final Set<MultiKey> actualObservations = observationContainer.getObservations();

		assertEquals(expectedObservations, actualObservations);

	}

	/**
	 * Tests
	 * {@link EnvironmentImpl#observeMaterialsProducerPropertyChange(boolean, MaterialsProducerId, MaterialsProducerPropertyId)}
	 *
	 */
	@Test
	@UnitTestMethod(name = "observeMaterialsProducerPropertyChange", args = {boolean.class,MaterialsProducerId.class, MaterialsProducerPropertyId.class})	
	public void testObserveMaterialsProducerPropertyChange() {
		/*
		 * We test for the post conditions by first having the components
		 * execute a series time-separated plans and then examining the
		 * observations recorded by each component. Precondition tests are added
		 * at the end.
		 *
		 * Actions
		 *
		 * Time 1 : Materials Producer 1 starts observation of Materials
		 * Producer 2 Property P
		 *
		 * Time 2 : Materials Producer 2 starts observation of Materials
		 * Producer 2 Property P
		 *
		 * Time 3 : Materials Producer 2 changes its Property P value
		 *
		 * Time 4 : Materials Producer 1 stops observation of Region 2 Property
		 * P
		 *
		 * Time 5 : Compartment 1 starts observation of Materials Producer 2
		 * Property P
		 *
		 * Time 6 : Materials Producer 2 changes its Property P value
		 *
		 * Expected observations
		 *
		 * Materials Producer 1: first property change --> demonstrates Post
		 * Conditions 1 and 3
		 *
		 * Materials Producer 2: no observations demonstrates Post Condition 4
		 *
		 * Compartment 1: second property change --> demonstrates Post
		 * Conditions 1 and 2
		 *
		 * All others: no observations --> demonstrates Post Condition 2
		 */
		final long seed = SEED_PROVIDER.getSeedValue(5);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		ScenarioBuilder scenarioBuilder = new UnstructuredScenarioBuilder();
		addStandardTrackingAndScenarioId(scenarioBuilder, randomGenerator);
		addStandardComponentsAndTypes(scenarioBuilder);
		addStandardPeople(scenarioBuilder, 10);
		ObservationContainer observationContainer = addObservationContainer(scenarioBuilder);
		addStandardPropertyDefinitions(scenarioBuilder, PropertyAssignmentPolicy.TRUE, randomGenerator);

		TaskPlanContainer taskPlanContainer = addTaskPlanContainer(scenarioBuilder);

		Scenario scenario = scenarioBuilder.build();

		Replication replication = getReplication(randomGenerator);

		int testTime = 1;

		/*
		 * Establish a non-boolean property so that we can have two distinct
		 * values different from the current value.
		 */
		TestMaterialsProducerPropertyId candidatePropertyId = null;
		for (final TestMaterialsProducerPropertyId materialsProcuderPropertyId : TestMaterialsProducerPropertyId.values()) {
			final PropertyDefinition propertyDefinition = scenario.getMaterialsProducerPropertyDefinition(materialsProcuderPropertyId);
			if (propertyDefinition.getType() != Boolean.class) {
				candidatePropertyId = materialsProcuderPropertyId;
				break;
			}
		}
		assertNotNull(candidatePropertyId);
		final TestMaterialsProducerPropertyId selectedMaterialsProducerPropertyId = candidatePropertyId;
		final PropertyDefinition propertyDefinition = scenario.getMaterialsProducerPropertyDefinition(selectedMaterialsProducerPropertyId);
		assertTrue(propertyDefinition.getDefaultValue().isPresent());
		final Object currentPropertyValue = propertyDefinition.getDefaultValue().get();
		Object propertyValue1 = null;
		while (currentPropertyValue.equals(propertyValue1) || (propertyValue1 == null)) {
			propertyValue1 = generatePropertyValue(propertyDefinition, randomGenerator);
		}
		assertNotNull(propertyValue1);
		assertFalse(propertyValue1.equals(currentPropertyValue));
		Object propertyValue2 = null;
		while (currentPropertyValue.equals(propertyValue2) || propertyValue1.equals(propertyValue2) || (propertyValue2 == null)) {
			propertyValue2 = generatePropertyValue(propertyDefinition, randomGenerator);
		}
		assertNotNull(propertyValue2);
		assertFalse(propertyValue2.equals(currentPropertyValue));
		assertFalse(propertyValue2.equals(propertyValue1));

		final Object firstPropertyValue = propertyValue1;
		final Object secondPropertyValue = propertyValue2;

		/*
		 * Time 1 : Materials Producer 1 starts observation of Materials
		 * Producer 2 Property P
		 */
		taskPlanContainer.addTaskPlan(TestMaterialsProducerId.MATERIALS_PRODUCER_1, testTime++, (environment) -> {
			environment.observeMaterialsProducerPropertyChange(true, TestMaterialsProducerId.MATERIALS_PRODUCER_2, selectedMaterialsProducerPropertyId);
		});

		/*
		 * Time 2 : Materials Producer 2 starts observation of Materials
		 * Producer 2 Property P
		 */
		taskPlanContainer.addTaskPlan(TestMaterialsProducerId.MATERIALS_PRODUCER_2, testTime++, (environment) -> {
			environment.observeMaterialsProducerPropertyChange(true, TestMaterialsProducerId.MATERIALS_PRODUCER_2, selectedMaterialsProducerPropertyId);
		});

		/*
		 * Time 3 : Materials Producer 2 changes its Property P value
		 */
		taskPlanContainer.addTaskPlan(TestMaterialsProducerId.MATERIALS_PRODUCER_2, testTime++, (environment) -> {
			environment.setMaterialsProducerPropertyValue(TestMaterialsProducerId.MATERIALS_PRODUCER_2, selectedMaterialsProducerPropertyId, firstPropertyValue);
		});

		/*
		 * Time 4 : Materials Producer 1 stops observation of Materials Producer
		 * 2 Property P
		 */
		taskPlanContainer.addTaskPlan(TestMaterialsProducerId.MATERIALS_PRODUCER_1, testTime++, (environment) -> {
			environment.observeMaterialsProducerPropertyChange(false, TestMaterialsProducerId.MATERIALS_PRODUCER_2, selectedMaterialsProducerPropertyId);
		});

		/*
		 * Time 5 : Compartment 1 starts observation of Materials Producer 2
		 * Property P
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.observeMaterialsProducerPropertyChange(true, TestMaterialsProducerId.MATERIALS_PRODUCER_2, selectedMaterialsProducerPropertyId);
		});

		/*
		 * Time 6 : Materials Producer 2 changes its Property P value
		 */
		taskPlanContainer.addTaskPlan(TestMaterialsProducerId.MATERIALS_PRODUCER_2, testTime++, (environment) -> {
			environment.setMaterialsProducerPropertyValue(TestMaterialsProducerId.MATERIALS_PRODUCER_2, selectedMaterialsProducerPropertyId, secondPropertyValue);
		});

		/*
		 * Precondition tests
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			// if the materials producer id is null
			assertModelException(() -> environment.observeMaterialsProducerPropertyChange(true, null, TestMaterialsProducerPropertyId.MATERIALS_PRODUCER_PROPERTY_1),
					SimulationErrorType.NULL_MATERIALS_PRODUCER_ID);
			// if the materials producer is unknown
			assertModelException(() -> environment.observeMaterialsProducerPropertyChange(true, TestMaterialsProducerId.getUnknownMaterialsProducerId(),
					TestMaterialsProducerPropertyId.MATERIALS_PRODUCER_PROPERTY_1), SimulationErrorType.UNKNOWN_MATERIALS_PRODUCER_ID);
			// if the property id is null
			assertModelException(() -> environment.observeMaterialsProducerPropertyChange(true, TestMaterialsProducerId.MATERIALS_PRODUCER_1, null),
					SimulationErrorType.NULL_MATERIALS_PRODUCER_PROPERTY_ID);
			// if the property is unknown
			assertModelException(() -> environment.observeMaterialsProducerPropertyChange(true, TestMaterialsProducerId.MATERIALS_PRODUCER_1,
					TestMaterialsProducerPropertyId.getUnknownMaterialsProducerPropertyId()), SimulationErrorType.UNKNOWN_MATERIALS_PRODUCER_PROPERTY_ID);
		});

		Simulation simulation = new Simulation();
		simulation.setReplication(replication);
		simulation.setScenario(scenario);
		simulation.execute();

		assertAllPlansExecuted(taskPlanContainer);

		final Set<MultiKey> expectedObservations = new LinkedHashSet<>();

		/*
		 * Materials Producer 1: first property change --> demonstrates Post
		 * Conditions 1 and 3
		 */

		expectedObservations.add(new MultiKey(3.0, TestMaterialsProducerId.MATERIALS_PRODUCER_1, ObservationType.MATERIALS_PRODUCER_PROPERTY, TestMaterialsProducerId.MATERIALS_PRODUCER_2,
				selectedMaterialsProducerPropertyId, firstPropertyValue));

		/*
		 * Materials Producer 2: no observations demonstrates Post Condition 4
		 */

		/*
		 * Compartment 1: second property change --> demonstrates Post
		 * Conditions 1 and 2
		 */

		expectedObservations.add(new MultiKey(6.0, TestCompartmentId.COMPARTMENT_1, ObservationType.MATERIALS_PRODUCER_PROPERTY, TestMaterialsProducerId.MATERIALS_PRODUCER_2,
				selectedMaterialsProducerPropertyId, secondPropertyValue));

		/*
		 * All others: no observations --> demonstrates Post Condition 2
		 */
		final Set<MultiKey> actualObservations = observationContainer.getObservations();

		assertEquals(expectedObservations, actualObservations);

	}

}
