package gcm.automated;

import static gcm.automated.support.EnvironmentSupport.addObservationContainer;
import static gcm.automated.support.EnvironmentSupport.addStandardComponentsAndTypes;
import static gcm.automated.support.EnvironmentSupport.addStandardPeople;
import static gcm.automated.support.EnvironmentSupport.addStandardPropertyDefinitions;
import static gcm.automated.support.EnvironmentSupport.addStandardTrackingAndScenarioId;
import static gcm.automated.support.EnvironmentSupport.addTaskPlanContainer;
import static gcm.automated.support.EnvironmentSupport.assertAllPlansExecuted;
import static gcm.automated.support.EnvironmentSupport.generatePropertyValue;
import static gcm.automated.support.EnvironmentSupport.getRandomGenerator;
import static gcm.automated.support.EnvironmentSupport.getReplication;
import static gcm.automated.support.ExceptionAssertion.assertModelException;
import static gcm.simulation.Filter.allPeople;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import org.apache.commons.math3.random.RandomGenerator;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import gcm.automated.support.EnvironmentSupport;
import gcm.automated.support.EnvironmentSupport.PropertyAssignmentPolicy;
import gcm.automated.support.ObservationContainer;
import gcm.automated.support.SeedProvider;
import gcm.automated.support.TaskPlanContainer;
import gcm.automated.support.TestCompartmentId;
import gcm.automated.support.TestGlobalComponentId;
import gcm.automated.support.TestPersonPropertyId;
import gcm.automated.support.TestRegionId;
import gcm.automated.support.TestRegionPropertyId;
import gcm.automated.support.TestResourceId;
import gcm.replication.Replication;
import gcm.scenario.CompartmentId;
import gcm.scenario.PersonId;
import gcm.scenario.PersonPropertyId;
import gcm.scenario.PropertyDefinition;
import gcm.scenario.RegionId;
import gcm.scenario.RegionPropertyId;
import gcm.scenario.ResourceId;
import gcm.scenario.Scenario;
import gcm.scenario.ScenarioBuilder;
import gcm.scenario.UnstructuredScenarioBuilder;
import gcm.simulation.EnvironmentImpl;
import gcm.simulation.ObservationType;
import gcm.simulation.Simulation;
import gcm.simulation.SimulationErrorType;
import gcm.util.MultiKey;
import gcm.util.annotations.UnitTest;
import gcm.util.annotations.UnitTestMethod;

@UnitTest(target = EnvironmentImpl.class)

public class AT_EnvironmentImpl_15 {

	private static SeedProvider SEED_PROVIDER;

	@BeforeClass
	public static void beforeClass() {
		SEED_PROVIDER = new SeedProvider(EnvironmentSupport.getMetaSeed(15));
	}

	/**
	 * Internal test(not part of public tests) to show that there are no large
	 * gaps in the seed cases generated by the SeedProvider.
	 */
	@AfterClass
	public static void afterClass() {
		// System.out.println(SEED_PROVIDER.generateUnusedSeedReport());
	}

	/**
	 * Tests
	 * {@link EnvironmentImpl#observeRegionPersonPropertyChange(boolean, RegionId, PersonPropertyId)}
	 */
	@Test
	@UnitTestMethod(name = "observeRegionPersonPropertyChange", args = { boolean.class, RegionId.class, PersonPropertyId.class })
	public void testObserveRegionPersonPropertyChange() {
		/*
		 * We test for the post conditions by first having the components
		 * execute a series time-separated plans and then examining the
		 * observations recorded by each component. Precondition tests are added
		 * at the end.
		 *
		 * Actions
		 *
		 * Time 1 : Global Component 1 starts observation of Person Property P
		 * constrained to Region2
		 *
		 * Time 2 : Region 2 starts observation of Person Property P constrained
		 * to Region2
		 *
		 * Time 3 : Region 2 changes a person's property value. The person is in
		 * Region2 and Compartment1
		 *
		 * Time 4 : Global Component 1 stops observation of Person Property P
		 *
		 * Time 5 : Compartment 2 starts observation of Person Property P
		 * constrained to Region2
		 *
		 * Time 6 : Global Component 2 changes the person's property
		 *
		 * Expected observations
		 *
		 * Global Component 1: first property change --> demonstrates Post
		 * Conditions 1 and 3
		 *
		 * Region 2: second property change --> demonstrates Post Condition 4
		 *
		 * Compartment 2: second property change --> demonstrates Post
		 * Conditions 1 and 2
		 *
		 * All others: no observations --> demonstrates Post Condition 2
		 */
		final long seed = SEED_PROVIDER.getSeedValue(0);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		ScenarioBuilder scenarioBuilder = new UnstructuredScenarioBuilder();
		addStandardTrackingAndScenarioId(scenarioBuilder, randomGenerator);
		addStandardComponentsAndTypes(scenarioBuilder);
		addStandardPeople(scenarioBuilder, 10);
		addStandardPropertyDefinitions(scenarioBuilder, PropertyAssignmentPolicy.TRUE, randomGenerator);

		ObservationContainer observationContainer = addObservationContainer(scenarioBuilder);

		TaskPlanContainer taskPlanContainer = addTaskPlanContainer(scenarioBuilder);

		Scenario scenario = scenarioBuilder.build();

		Replication replication = getReplication(randomGenerator);

		int testTime = 1;

		/*
		 * Establish a non-boolean property so that we can have two distinct
		 * values different from the current value.
		 */
		TestPersonPropertyId candidatePropertyId = null;
		for (final TestPersonPropertyId personPropertyId : TestPersonPropertyId.values()) {
			final PropertyDefinition propertyDefinition = scenario.getPersonPropertyDefinition(personPropertyId);
			if (propertyDefinition.getType() != Boolean.class) {
				candidatePropertyId = personPropertyId;
				break;
			}

		}
		assertNotNull(candidatePropertyId);
		final TestPersonPropertyId selectedPersonPropertyId = candidatePropertyId;

		final PropertyDefinition propertyDefinition = scenario.getPersonPropertyDefinition(selectedPersonPropertyId);
		assertTrue(propertyDefinition.getDefaultValue().isPresent());
		final Object currentPropertyValue = propertyDefinition.getDefaultValue().get();
		Object propertyValue1 = null;
		while (currentPropertyValue.equals(propertyValue1) || (propertyValue1 == null)) {
			propertyValue1 = generatePropertyValue(propertyDefinition, randomGenerator);
		}
		assertNotNull(propertyValue1);
		assertFalse(propertyValue1.equals(currentPropertyValue));
		Object propertyValue2 = null;
		while (currentPropertyValue.equals(propertyValue2) || propertyValue1.equals(propertyValue2) || (propertyValue2 == null)) {
			propertyValue2 = generatePropertyValue(propertyDefinition, randomGenerator);
		}
		assertNotNull(propertyValue2);
		assertFalse(propertyValue2.equals(currentPropertyValue));
		assertFalse(propertyValue2.equals(propertyValue1));

		final Object firstPropertyValue = propertyValue1;
		final Object secondPropertyValue = propertyValue2;

		final List<PersonId> peopleInRegion2Compartment1 = new ArrayList<>();
		for (final PersonId personId : scenario.getPeopleIds()) {
			final CompartmentId personCompartment = scenario.getPersonCompartment(personId);
			if (personCompartment.equals(TestCompartmentId.COMPARTMENT_1)) {
				final RegionId personRegion = scenario.getPersonRegion(personId);
				if (personRegion.equals(TestRegionId.REGION_2)) {
					peopleInRegion2Compartment1.add(personId);
				}
			}
		}
		assertTrue(peopleInRegion2Compartment1.size() >= 1);
		final PersonId selectedPersonId = peopleInRegion2Compartment1.get(0);

		/*
		 * Time 1 : Global Component 1 starts observation of Person Property P
		 * constrained to Region 2
		 */

		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.observeRegionPersonPropertyChange(true, TestRegionId.REGION_2, selectedPersonPropertyId);
		});

		/*
		 * Time 2 : Region 2 starts observation of Person Property P constrained
		 * to Region2
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_2, testTime++, (environment) -> {
			environment.observeRegionPersonPropertyChange(true, TestRegionId.REGION_2, selectedPersonPropertyId);
		});

		/*
		 * Time 3 : Region 2 changes a person's property value. The person is in
		 * Region 2 and Compartment 1
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_2, testTime++, (environment) -> {
			environment.setPersonPropertyValue(selectedPersonId, selectedPersonPropertyId, firstPropertyValue);
		});

		/*
		 * Time 4 : Global Component 1 stops observation of Person Property P
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.observeRegionPersonPropertyChange(false, TestRegionId.REGION_2, selectedPersonPropertyId);
		});

		/*
		 * Time 5 : Compartment 2 starts observation of Person Property P
		 * constrained to Region 2
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_2, testTime++, (environment) -> {
			environment.observeRegionPersonPropertyChange(true, TestRegionId.REGION_2, selectedPersonPropertyId);
		});

		/*
		 * Time 6 : Global Component 2 changes the person's property
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_2, testTime++, (environment) -> {
			environment.setPersonPropertyValue(selectedPersonId, selectedPersonPropertyId, secondPropertyValue);
		});

		/*
		 * Precondition tests
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			// if the property id is null
			assertModelException(() -> environment.observeRegionPersonPropertyChange(true, TestRegionId.REGION_1, null), SimulationErrorType.NULL_PERSON_PROPERTY_ID);
			// if the property is unknown
			assertModelException(() -> environment.observeRegionPersonPropertyChange(true, TestRegionId.REGION_1, TestPersonPropertyId.getUnknownPersonPropertyId()),
					SimulationErrorType.UNKNOWN_PERSON_PROPERTY_ID);
			// if the region id is null
			assertModelException(() -> environment.observeRegionPersonPropertyChange(true, null, TestPersonPropertyId.PERSON_PROPERTY_1), SimulationErrorType.NULL_REGION_ID);
			// if the region id is unknown
			assertModelException(() -> environment.observeRegionPersonPropertyChange(true, TestRegionId.getUnknownRegionId(), TestPersonPropertyId.PERSON_PROPERTY_1),
					SimulationErrorType.UNKNOWN_REGION_ID);
		});

		Simulation simulation = new Simulation();
		simulation.setReplication(replication);
		simulation.setScenario(scenario);
		simulation.execute();

		assertAllPlansExecuted(taskPlanContainer);

		final Set<MultiKey> expectedObservations = new LinkedHashSet<>();

		/*
		 * Expected observations
		 *
		 * Global Component 1 1: first property change --> demonstrates Post
		 * Conditions 1 and 3
		 */

		expectedObservations.add(new MultiKey(3.0, TestGlobalComponentId.GLOBAL_COMPONENT_1, ObservationType.PERSON_PROPERTY, selectedPersonId, selectedPersonPropertyId, firstPropertyValue));

		/*
		 * Compartment 2: second property change --> demonstrates Post Condition
		 * 4
		 */
		expectedObservations.add(new MultiKey(6.0, TestRegionId.REGION_2, ObservationType.PERSON_PROPERTY, selectedPersonId, selectedPersonPropertyId, secondPropertyValue));

		/*
		 * Region 2: second property change --> demonstrates Post Conditions 1
		 * and 2
		 */
		expectedObservations.add(new MultiKey(6.0, TestCompartmentId.COMPARTMENT_2, ObservationType.PERSON_PROPERTY, selectedPersonId, selectedPersonPropertyId, secondPropertyValue));
		/*
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		final Set<MultiKey> actualObservations = observationContainer.getObservations();

		assertEquals(expectedObservations, actualObservations);

	}

	/**
	 * Tests
	 * {@link EnvironmentImpl#observeRegionPersonResourceChange(boolean, RegionId, ResourceId)}
	 *
	 */
	@Test
	@UnitTestMethod(name = "observeRegionPersonResourceChange", args = { boolean.class, RegionId.class, ResourceId.class })
	public void testObserveRegionPersonResourceChange() {
		/*
		 * We test for the post conditions by first having the components
		 * execute a series time-separated plans and then examining the
		 * observations recorded by each component. Precondition tests are added
		 * at the end.
		 *
		 * Actions
		 *
		 * Time 1 : Compartment 1 starts observation of person's Resource Level.
		 * Person will be in Compartment 1 and Region 1.
		 *
		 * Time 2 : Region 1 starts observation of person's Resource Level
		 *
		 * Time 3 : Compartment 2 starts observation of person's Resource Level
		 *
		 * Time 4 : Region 1 changes person's Resource Level by transfer to
		 * person from Region 1
		 *
		 * Time 5 : Global Component 1 starts observation of person's Resource
		 * Level
		 *
		 * Time 6 : Compartment 2 stops observation of person's Resource Level
		 *
		 * Time 7 : Region 1 changes person's resource level by transfer from
		 * person to Region 1
		 *
		 * Time 8 : Compartment 1 changes person's Resource Level by removing
		 * resource from person
		 *
		 * Expected observations
		 *
		 * Compartment 1: first and second resource changes --> demonstrates
		 * Post Conditions 1 and 4
		 *
		 * Compartment 2: first resource change --> demonstrates Post Condition
		 * 1 and 3
		 *
		 * Region 1: third property changes --> demonstrates Post Conditions 1
		 * and 4
		 *
		 * Global Component 1: second and third property changes -->
		 * demonstrates Post Conditions 1 and 2
		 *
		 * All others: no observations --> demonstrates Post Condition 2
		 */
		final long seed = SEED_PROVIDER.getSeedValue(1);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		ScenarioBuilder scenarioBuilder = new UnstructuredScenarioBuilder();
		addStandardTrackingAndScenarioId(scenarioBuilder, randomGenerator);
		addStandardComponentsAndTypes(scenarioBuilder);
		addStandardPeople(scenarioBuilder, 10);
		addStandardPropertyDefinitions(scenarioBuilder, PropertyAssignmentPolicy.TRUE, randomGenerator);

		ObservationContainer observationContainer = addObservationContainer(scenarioBuilder);

		TaskPlanContainer taskPlanContainer = addTaskPlanContainer(scenarioBuilder);

		Scenario scenario = scenarioBuilder.build();

		Replication replication = getReplication(randomGenerator);

		int testTime = 1;

		/*
		 * Select a resource
		 */
		final TestResourceId selectedResourceId = TestResourceId.getRandomResourceId(randomGenerator);

		/*
		 * Select a person from Compartment 1, Region 1
		 */
		final List<PersonId> peopleInCompartment1AndRegion1 = new ArrayList<>();
		for (final PersonId personId : scenario.getPeopleIds()) {
			final CompartmentId personCompartment = scenario.getPersonCompartment(personId);
			if (personCompartment.equals(TestCompartmentId.COMPARTMENT_1)) {
				final RegionId personRegion = scenario.getPersonRegion(personId);
				if (personRegion.equals(TestRegionId.REGION_1)) {
					peopleInCompartment1AndRegion1.add(personId);
				}
			}
		}
		assertTrue(peopleInCompartment1AndRegion1.size() >= 1);
		final int personIndex = randomGenerator.nextInt(peopleInCompartment1AndRegion1.size());
		final PersonId selectedPersonId = peopleInCompartment1AndRegion1.get(personIndex);

		/*
		 * select amounts to move and calculate expected resulting resource
		 * levels for the selected person and resource
		 */
		final long firstAmount = 1000;
		final long secondAmount = 300;
		final long thirdAmount = 400;

		final long expectedFirstLevel = firstAmount;
		final long expectedSecondLevel = firstAmount - secondAmount;
		final long expectedThirdLevel = expectedSecondLevel - thirdAmount;

		/*
		 * Time 1 : Compartment 1 starts observation of person's Resource Level.
		 * Person will be in Compartment 1 and Region 1.
		 */

		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.observeRegionPersonResourceChange(true, TestRegionId.REGION_1, selectedResourceId);
		});

		/*
		 * Time 2 : Region 1 starts observation of person's Resource Level
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.observeRegionPersonResourceChange(true, TestRegionId.REGION_1, selectedResourceId);
		});

		/*
		 * Time 3 : Compartment 2 starts observation of person's Resource Level
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_2, testTime++, (environment) -> {
			environment.observeRegionPersonResourceChange(true, TestRegionId.REGION_1, selectedResourceId);
		});

		/*
		 * Time 4 :Region 1 changes person's Resource Level by transfer to
		 * person from Region 1
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.addResourceToRegion(selectedResourceId, TestRegionId.REGION_1, firstAmount);
			environment.transferResourceToPerson(selectedResourceId, selectedPersonId, firstAmount);
		});

		/*
		 * Time 5 : Global Component 1 starts observation of person's Resource
		 * Level
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.observeRegionPersonResourceChange(true, TestRegionId.REGION_1, selectedResourceId);
		});

		/*
		 * Time 6 : Compartment 2 stops observation of person's Resource Level
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_2, testTime++, (environment) -> {
			environment.observeRegionPersonResourceChange(false, TestRegionId.REGION_1, selectedResourceId);
		});

		/*
		 * Time 7 : Region 1 changes person's resource level by transfer from
		 * person to Region 1
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.transferResourceFromPerson(selectedResourceId, selectedPersonId, secondAmount);
		});
		/*
		 * Time 8 : Compartment 1 changes person's Resource Level by removing
		 * resource from person
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.removeResourceFromPerson(selectedResourceId, selectedPersonId, thirdAmount);
		});

		/*
		 * Precondition tests
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			final Object key = new Object();
			environment.addPopulationIndex(allPeople(), key);
			Optional<PersonId> optional = environment.getRandomIndexedPerson(key);
			assertTrue(optional.isPresent());

			// if the resource id is null
			assertModelException(() -> environment.observeRegionPersonResourceChange(true, TestRegionId.REGION_1, null), SimulationErrorType.NULL_RESOURCE_ID);
			// if the resource id is unknown
			assertModelException(() -> environment.observeRegionPersonResourceChange(true, TestRegionId.REGION_1, TestResourceId.getUnknownResourceId()), SimulationErrorType.UNKNOWN_RESOURCE_ID);
			// if the region id is null
			assertModelException(() -> environment.observeRegionPersonResourceChange(true, null, TestResourceId.RESOURCE1), SimulationErrorType.NULL_REGION_ID);
			// if the region id is unknown
			assertModelException(() -> environment.observeRegionPersonResourceChange(true, TestRegionId.getUnknownRegionId(), TestResourceId.RESOURCE1), SimulationErrorType.UNKNOWN_REGION_ID);

			environment.removePopulationIndex(key);

		});

		Simulation simulation = new Simulation();
		simulation.setReplication(replication);
		simulation.setScenario(scenario);
		simulation.execute();

		assertAllPlansExecuted(taskPlanContainer);

		final Set<MultiKey> expectedObservations = new LinkedHashSet<>();

		/*
		 * Compartment 1: first and second resource changes --> demonstrates
		 * Post Conditions 1 and 4
		 */
		expectedObservations.add(new MultiKey(4.0, TestCompartmentId.COMPARTMENT_1, ObservationType.PERSON_RESOURCE, selectedPersonId, selectedResourceId, expectedFirstLevel));

		expectedObservations.add(new MultiKey(7.0, TestCompartmentId.COMPARTMENT_1, ObservationType.PERSON_RESOURCE, selectedPersonId, selectedResourceId, expectedSecondLevel));

		/*
		 * Compartment 2: first resource change --> demonstrates Post Condition
		 * 1 and 3
		 */

		expectedObservations.add(new MultiKey(4.0, TestCompartmentId.COMPARTMENT_2, ObservationType.PERSON_RESOURCE, selectedPersonId, selectedResourceId, expectedFirstLevel));

		/*
		 * Region 1: third property changes --> demonstrates Post Conditions 1
		 * and 4
		 */

		expectedObservations.add(new MultiKey(8.0, TestRegionId.REGION_1, ObservationType.PERSON_RESOURCE, selectedPersonId, selectedResourceId, expectedThirdLevel));

		/*
		 * Global Component 1: second and third property changes -->
		 * demonstrates Post Conditions 1 and 2
		 */
		expectedObservations.add(new MultiKey(7.0, TestGlobalComponentId.GLOBAL_COMPONENT_1, ObservationType.PERSON_RESOURCE, selectedPersonId, selectedResourceId, expectedSecondLevel));

		expectedObservations.add(new MultiKey(8.0, TestGlobalComponentId.GLOBAL_COMPONENT_1, ObservationType.PERSON_RESOURCE, selectedPersonId, selectedResourceId, expectedThirdLevel));

		/*
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		final Set<MultiKey> actualObservations = observationContainer.getObservations();

		assertEquals(expectedObservations, actualObservations);

	}

	/**
	 * Tests
	 * {@link EnvironmentImpl#observeRegionPersonArrival(boolean, RegionId)}
	 *
	 */
	@Test
	@UnitTestMethod(name = "observeRegionPersonArrival", args = { boolean.class, RegionId.class })
	public void testObserveRegionPersonArrival() {
		/*
		 * We test for the post conditions by first having the components
		 * execute a series time-separated plans and then examining the
		 * observations recorded by each component. Precondition tests are added
		 * at the end.
		 *
		 * Actions
		 *
		 * Time 1 : Region 1 starts observation of Region 2
		 *
		 * Time 2 : Compartment 1 starts observation of Region 2
		 *
		 * Time 3 : Region 3 starts observation
		 *
		 * Time 4 : Global Component 1 starts observation and moves a person to
		 * Region 2
		 *
		 * Time 5 : Region 2 starts observation of Region 2
		 *
		 * Time 6 : Region 1 stops observation
		 *
		 * Time 7 : Global Component 1 moves another person to Region 2
		 *
		 * Expected observations
		 *
		 * Region 1: first person --> demonstrates Post Conditions 1 and 3
		 *
		 * Region 2: second person --> demonstrates Post Conditions 2 and 4
		 *
		 * Region 3: first and second person --> demonstrates Post Condition 1
		 *
		 * Compartment 1: first and second person --> demonstrates Post
		 * Conditions 1
		 *
		 * Global Component 1: second person --> demonstrates Post Condition and
		 * 4
		 *
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		final long seed = SEED_PROVIDER.getSeedValue(2);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		ScenarioBuilder scenarioBuilder = new UnstructuredScenarioBuilder();
		addStandardTrackingAndScenarioId(scenarioBuilder, randomGenerator);
		addStandardComponentsAndTypes(scenarioBuilder);
		addStandardPeople(scenarioBuilder, 10);
		ObservationContainer observationContainer = addObservationContainer(scenarioBuilder);
		addStandardPropertyDefinitions(scenarioBuilder, PropertyAssignmentPolicy.RANDOM, randomGenerator);

		TaskPlanContainer taskPlanContainer = addTaskPlanContainer(scenarioBuilder);

		Scenario scenario = scenarioBuilder.build();

		Replication replication = getReplication(randomGenerator);

		int testTime = 1;

		PersonId personToFind = null;
		for (final PersonId personId : scenario.getPeopleIds()) {
			if (scenario.getPersonRegion(personId).equals(TestRegionId.REGION_4)) {
				personToFind = personId;
				break;
			}
		}
		assertNotNull(personToFind);
		final PersonId firstPersonId = personToFind;

		personToFind = null;
		for (final PersonId personId : scenario.getPeopleIds()) {
			if (scenario.getPersonRegion(personId).equals(TestRegionId.REGION_3)) {
				personToFind = personId;
				break;
			}
		}
		assertNotNull(personToFind);
		final PersonId secondPersonId = personToFind;
		/*
		 *
		 * Time 1 : Region 1 starts observation of Region 2
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.observeRegionPersonArrival(true, TestRegionId.REGION_2);
		});

		/*
		 * Time 2 : Compartment 1 starts observation of Region 2
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.observeRegionPersonArrival(true, TestRegionId.REGION_2);
		});

		/*
		 * Time 3 : Region 3 starts observation
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_3, testTime++, (environment) -> {
			environment.observeRegionPersonArrival(true, TestRegionId.REGION_2);
		});

		/*
		 * Time 4 : Global Component 1 starts observation and moves a person to
		 * Region 2
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.observeRegionPersonArrival(true, TestRegionId.REGION_2);
			environment.setPersonRegion(firstPersonId, TestRegionId.REGION_2);
		});

		/*
		 * Time 5 : Region 2 starts observation of Region 2
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_2, testTime++, (environment) -> {
			environment.observeRegionPersonArrival(true, TestRegionId.REGION_2);
		});

		/*
		 * Time 6 : Region 1 stops observation
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.observeRegionPersonArrival(false, TestRegionId.REGION_2);
		});

		/*
		 * Time 7 : Global Component 1 moves another person to Region 2
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.setPersonRegion(secondPersonId, TestRegionId.REGION_2);
		});

		/*
		 * Precondition tests
		 *
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			// if the region id is null
			assertModelException(() -> environment.observeRegionPersonArrival(false, null), SimulationErrorType.NULL_REGION_ID);
			// if the region is unknown
			assertModelException(() -> environment.observeRegionPersonArrival(false, TestRegionId.getUnknownRegionId()), SimulationErrorType.UNKNOWN_REGION_ID);
		});

		Simulation simulation = new Simulation();
		simulation.setReplication(replication);
		simulation.setScenario(scenario);
		simulation.execute();

		assertAllPlansExecuted(taskPlanContainer);

		final Set<MultiKey> expectedObservations = new LinkedHashSet<>();

		/*
		 * Region 1: first person --> demonstrates Post Conditions 1 and 3
		 */
		expectedObservations.add(new MultiKey(4.0, TestRegionId.REGION_1, ObservationType.REGION_PERSON_ARRIVAL, firstPersonId));

		/*
		 * Region 2: second person --> demonstrates Post Conditions 2 and 4
		 */
		expectedObservations.add(new MultiKey(4.0, TestRegionId.REGION_3, ObservationType.REGION_PERSON_ARRIVAL, firstPersonId));
		expectedObservations.add(new MultiKey(7.0, TestRegionId.REGION_2, ObservationType.REGION_PERSON_ARRIVAL, secondPersonId));

		/*
		 * Region 3: first and second person --> demonstrates Post Condition 1
		 */
		expectedObservations.add(new MultiKey(7.0, TestRegionId.REGION_3, ObservationType.REGION_PERSON_ARRIVAL, secondPersonId));
		/*
		 * Compartment 1: first and second person --> demonstrates Post
		 * Conditions 1
		 */
		expectedObservations.add(new MultiKey(4.0, TestCompartmentId.COMPARTMENT_1, ObservationType.REGION_PERSON_ARRIVAL, firstPersonId));
		expectedObservations.add(new MultiKey(7.0, TestCompartmentId.COMPARTMENT_1, ObservationType.REGION_PERSON_ARRIVAL, secondPersonId));

		/*
		 * Global Component 1: second person --> demonstrates Post Condition and
		 * 4
		 *
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		final Set<MultiKey> actualObservations = observationContainer.getObservations();

		assertEquals(expectedObservations, actualObservations);

	}

	/**
	 * Tests
	 * {@link EnvironmentImpl#observeRegionPersonDeparture(boolean, RegionId)}
	 *
	 */
	@Test
	@UnitTestMethod(name = "observeRegionPersonDeparture", args = { boolean.class, RegionId.class })
	public void testObserveRegionPersonDeparture() {
		/*
		 * We test for the post conditions by first having the components
		 * execute a series time-separated plans and then examining the
		 * observations recorded by each component. Precondition tests are added
		 * at the end.
		 *
		 * Actions
		 *
		 * Time 1 : Region 1 starts observation of Region 2
		 *
		 * Time 2 : Compartment 1 starts observation of Region 2
		 *
		 * Time 3 : Region 3 starts observation
		 *
		 * Time 4 : Global Component 1 starts observation and moves a first
		 * person from Region 2 to Region 4
		 *
		 * Time 5 : Region 2 starts observation of Region 2
		 *
		 * Time 6 : Region 1 stops observation
		 *
		 * Time 7 : Global Component 1 moves a second person from Region 2 to
		 * Region 3
		 *
		 * Expected observations
		 *
		 * Region 1: first person --> demonstrates Post Conditions 1 and 3
		 *
		 * Region 2: second person --> demonstrates Post Conditions 2 and 4
		 *
		 * Region 3: first and second person --> demonstrates Post Condition 1
		 *
		 * Compartment 1: first and second person --> demonstrates Post
		 * Conditions 1
		 *
		 * Global Component 1: second person --> demonstrates Post Condition and
		 * 4
		 *
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		final long seed = SEED_PROVIDER.getSeedValue(3);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		ScenarioBuilder scenarioBuilder = new UnstructuredScenarioBuilder();
		addStandardTrackingAndScenarioId(scenarioBuilder, randomGenerator);
		addStandardComponentsAndTypes(scenarioBuilder);
		addStandardPeople(scenarioBuilder, 10);
		ObservationContainer observationContainer = addObservationContainer(scenarioBuilder);
		addStandardPropertyDefinitions(scenarioBuilder, PropertyAssignmentPolicy.RANDOM, randomGenerator);

		TaskPlanContainer taskPlanContainer = addTaskPlanContainer(scenarioBuilder);

		Scenario scenario = scenarioBuilder.build();

		Replication replication = getReplication(randomGenerator);

		int testTime = 1;

		/*
		 *
		 * Time 1 : Region 1 starts observation of Region 2
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.observeRegionPersonDeparture(true, TestRegionId.REGION_2);
		});

		/*
		 * Time 2 : Compartment 1 starts observation of Region 2
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.observeRegionPersonDeparture(true, TestRegionId.REGION_2);
		});

		/*
		 * Time 3 : Region 3 starts observation
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_3, testTime++, (environment) -> {
			environment.observeRegionPersonDeparture(true, TestRegionId.REGION_2);
		});

		/*
		 * Time 4 : Global Component 1 starts observation and moves a first
		 * person from Region 2 to Region 4
		 */
		final List<PersonId> peopleInRegion2 = new ArrayList<>();
		for (final PersonId personId : scenario.getPeopleIds()) {
			if (scenario.getPersonRegion(personId).equals(TestRegionId.REGION_2)) {
				peopleInRegion2.add(personId);
				if (peopleInRegion2.size() >= 2) {
					break;
				}
			}
		}

		assertTrue(peopleInRegion2.size() >= 2);

		final PersonId firstPersonId = peopleInRegion2.get(0);
		final PersonId secondPersonId = peopleInRegion2.get(1);

		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.observeRegionPersonDeparture(true, TestRegionId.REGION_2);
			environment.setPersonRegion(firstPersonId, TestRegionId.REGION_4);
		});

		/*
		 * Time 5 : Region 2 starts observation of Region 2
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_2, testTime++, (environment) -> {
			environment.observeRegionPersonDeparture(true, TestRegionId.REGION_2);
		});

		/*
		 * Time 6 : Region 1 stops observation
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.observeRegionPersonDeparture(false, TestRegionId.REGION_2);
		});

		/*
		 * Time 7 : Global Component 1 moves a second person from Region 2 to
		 * Region 3
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			environment.setPersonRegion(secondPersonId, TestRegionId.REGION_3);
		});

		/*
		 * Precondition tests
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			// if the region id is null
			assertModelException(() -> environment.observeRegionPersonDeparture(true, null), SimulationErrorType.NULL_REGION_ID);
			// if the region is unknown
			assertModelException(() -> environment.observeRegionPersonDeparture(true, TestRegionId.getUnknownRegionId()), SimulationErrorType.UNKNOWN_REGION_ID);
		});

		Simulation simulation = new Simulation();
		simulation.setReplication(replication);
		simulation.setScenario(scenario);
		simulation.execute();

		assertAllPlansExecuted(taskPlanContainer);

		final Set<MultiKey> expectedObservations = new LinkedHashSet<>();

		/*
		 * Region 1: first person --> demonstrates Post Conditions 1 and 3
		 */
		expectedObservations.add(new MultiKey(4.0, TestRegionId.REGION_1, ObservationType.REGION_PERSON_DEPARTURE, TestRegionId.REGION_2, firstPersonId));

		/*
		 * Region 2: second person --> demonstrates Post Conditions 2 and 4
		 */
		expectedObservations.add(new MultiKey(4.0, TestRegionId.REGION_3, ObservationType.REGION_PERSON_DEPARTURE, TestRegionId.REGION_2, firstPersonId));
		expectedObservations.add(new MultiKey(7.0, TestRegionId.REGION_2, ObservationType.REGION_PERSON_DEPARTURE, TestRegionId.REGION_2, secondPersonId));

		/*
		 * Region 3: first and second person --> demonstrates Post Condition 1
		 */
		expectedObservations.add(new MultiKey(7.0, TestRegionId.REGION_3, ObservationType.REGION_PERSON_DEPARTURE, TestRegionId.REGION_2, secondPersonId));
		/*
		 * Compartment 1: first and second person --> demonstrates Post
		 * Conditions 1
		 */
		expectedObservations.add(new MultiKey(4.0, TestCompartmentId.COMPARTMENT_1, ObservationType.REGION_PERSON_DEPARTURE, TestRegionId.REGION_2, firstPersonId));
		expectedObservations.add(new MultiKey(7.0, TestCompartmentId.COMPARTMENT_1, ObservationType.REGION_PERSON_DEPARTURE, TestRegionId.REGION_2, secondPersonId));

		/*
		 * Global Component 1: second person --> demonstrates Post Condition and
		 * 4
		 *
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		final Set<MultiKey> actualObservations = observationContainer.getObservations();

		assertEquals(expectedObservations, actualObservations);

	}

	/**
	 * Tests
	 * {@link EnvironmentImpl#observeRegionPropertyChange(boolean, RegionId, RegionPropertyId)}
	 *
	 */
	@Test
	@UnitTestMethod(name = "observeRegionPropertyChange", args = { boolean.class, RegionId.class, RegionPropertyId.class })
	public void testObserveRegionPropertyChange() {
		/*
		 * We test for the post conditions by first having the components
		 * execute a series time-separated plans and then examining the
		 * observations recorded by each component. Precondition tests are added
		 * at the end.
		 *
		 * Actions
		 *
		 * Time 1 : Region 1 starts observation of Region 2 Property P
		 *
		 * Time 2 : Region 2 starts observation of Region 2 Property P
		 *
		 * Time 3 : Region 2 changes its Property P value
		 *
		 * Time 4 : Region 1 stops observation of Region 2 Property P
		 *
		 * Time 5 : Compartment 1 starts observation of Region 2 Property P
		 *
		 * Time 6 : Region 2 changes its Property P value
		 *
		 * Expected observations
		 *
		 * Region 1: first property change --> demonstrates Post Conditions 1
		 * and 3
		 *
		 * Region 2: no observations demonstrates Post Condition 4
		 *
		 * Compartment 1: second property change --> demonstrates Post
		 * Conditions 1 and 2
		 *
		 * All others: no observations --> demonstrates Post Condition 2
		 */

		final long seed = SEED_PROVIDER.getSeedValue(4);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		ScenarioBuilder scenarioBuilder = new UnstructuredScenarioBuilder();
		addStandardTrackingAndScenarioId(scenarioBuilder, randomGenerator);
		addStandardComponentsAndTypes(scenarioBuilder);
		addStandardPeople(scenarioBuilder, 10);
		addStandardPropertyDefinitions(scenarioBuilder, PropertyAssignmentPolicy.TRUE, randomGenerator);

		ObservationContainer observationContainer = addObservationContainer(scenarioBuilder);

		TaskPlanContainer taskPlanContainer = addTaskPlanContainer(scenarioBuilder);

		Scenario scenario = scenarioBuilder.build();

		Replication replication = getReplication(randomGenerator);

		int testTime = 1;

		/*
		 * Establish a non-boolean property so that we can have two distinct
		 * values different from the current value.
		 */
		TestRegionPropertyId candidatePropertyId = null;
		for (final TestRegionPropertyId regionPropertyId : TestRegionPropertyId.values()) {
			final PropertyDefinition propertyDefinition = scenario.getRegionPropertyDefinition(regionPropertyId);
			if (propertyDefinition.getType() != Boolean.class) {
				candidatePropertyId = regionPropertyId;
				break;
			}

		}
		assertNotNull(candidatePropertyId);
		final TestRegionPropertyId selectedRegionPropertyId = candidatePropertyId;
		final PropertyDefinition propertyDefinition = scenario.getRegionPropertyDefinition(selectedRegionPropertyId);
		assertTrue(propertyDefinition.getDefaultValue().isPresent());
		final Object currentPropertyValue = propertyDefinition.getDefaultValue().get();
		Object propertyValue1 = null;
		while (currentPropertyValue.equals(propertyValue1) || (propertyValue1 == null)) {
			propertyValue1 = generatePropertyValue(propertyDefinition, randomGenerator);
		}
		assertNotNull(propertyValue1);
		assertFalse(propertyValue1.equals(currentPropertyValue));
		Object propertyValue2 = null;
		while (currentPropertyValue.equals(propertyValue2) || propertyValue1.equals(propertyValue2) || (propertyValue2 == null)) {
			propertyValue2 = generatePropertyValue(propertyDefinition, randomGenerator);
		}
		assertNotNull(propertyValue2);
		assertFalse(propertyValue2.equals(currentPropertyValue));
		assertFalse(propertyValue2.equals(propertyValue1));

		final Object firstPropertyValue = propertyValue1;
		final Object secondPropertyValue = propertyValue2;

		/*
		 * Time 1 : Region 1 starts observation of Region 2 Property P
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.observeRegionPropertyChange(true, TestRegionId.REGION_2, selectedRegionPropertyId);
		});

		/*
		 * Time 2 : Region 2 starts observation of Region 2 Property P
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_2, testTime++, (environment) -> {
			environment.observeRegionPropertyChange(true, TestRegionId.REGION_2, selectedRegionPropertyId);
		});

		/*
		 * Time 3 : Region 2 changes its Property P value
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_2, testTime++, (environment) -> {
			environment.setRegionPropertyValue(TestRegionId.REGION_2, selectedRegionPropertyId, firstPropertyValue);
		});

		/*
		 * Time 4 : Region 1 stops observation of Region 2 Property P
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_1, testTime++, (environment) -> {
			environment.observeRegionPropertyChange(false, TestRegionId.REGION_2, selectedRegionPropertyId);
		});

		/*
		 * Time 5 : Compartment 1 starts observation of Region 2 Property P
		 */
		taskPlanContainer.addTaskPlan(TestCompartmentId.COMPARTMENT_1, testTime++, (environment) -> {
			environment.observeRegionPropertyChange(true, TestRegionId.REGION_2, selectedRegionPropertyId);
		});

		/*
		 * Time 6 : Region 2 changes its Property P value
		 */
		taskPlanContainer.addTaskPlan(TestRegionId.REGION_2, testTime++, (environment) -> {
			environment.setRegionPropertyValue(TestRegionId.REGION_2, selectedRegionPropertyId, secondPropertyValue);
		});

		/*
		 * Precondition tests
		 */
		taskPlanContainer.addTaskPlan(TestGlobalComponentId.GLOBAL_COMPONENT_1, testTime++, (environment) -> {
			// if the region id is null
			assertModelException(() -> environment.observeRegionPropertyChange(true, null, TestRegionPropertyId.REGION_PROPERTY_1), SimulationErrorType.NULL_REGION_ID);
			// if the region is unknown
			assertModelException(() -> environment.observeRegionPropertyChange(true, TestRegionId.getUnknownRegionId(), TestRegionPropertyId.REGION_PROPERTY_1), SimulationErrorType.UNKNOWN_REGION_ID);
			// if the property id is null
			assertModelException(() -> environment.observeRegionPropertyChange(true, TestRegionId.REGION_1, null), SimulationErrorType.NULL_REGION_PROPERTY_ID);
			// if the property is unknown
			assertModelException(() -> environment.observeRegionPropertyChange(true, TestRegionId.REGION_1, TestRegionPropertyId.getUnknownRegionPropertyId()),
					SimulationErrorType.UNKNOWN_REGION_PROPERTY_ID);
		});

		Simulation simulation = new Simulation();
		simulation.setReplication(replication);
		simulation.setScenario(scenario);
		simulation.execute();

		assertAllPlansExecuted(taskPlanContainer);

		final Set<MultiKey> expectedObservations = new LinkedHashSet<>();

		/*
		 * Region 1: first property change --> demonstrates Post Conditions 1
		 * and 3
		 */

		expectedObservations.add(new MultiKey(3.0, TestRegionId.REGION_1, ObservationType.REGION_PROPERTY, TestRegionId.REGION_2, selectedRegionPropertyId, firstPropertyValue));

		/*
		 * Region 2: no observations demonstrates Post Condition 4
		 */

		/*
		 * Compartment 1: second property change --> demonstrates Post
		 * Conditions 1 and 2
		 */

		expectedObservations.add(new MultiKey(6.0, TestCompartmentId.COMPARTMENT_1, ObservationType.REGION_PROPERTY, TestRegionId.REGION_2, selectedRegionPropertyId, secondPropertyValue));

		/*
		 * All others: no observations --> demonstrates Post Condition 2
		 */
		final Set<MultiKey> actualObservations = observationContainer.getObservations();

		assertEquals(expectedObservations, actualObservations);

	}

}
