package gcm.automated;

import static gcm.automated.support.EnvironmentSupport.getRandomGenerator;
import static gcm.automated.support.ExceptionAssertion.assertException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.util.LinkedHashSet;
import java.util.Set;

import org.apache.commons.math3.random.RandomGenerator;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import gcm.automated.support.SeedProvider;
import gcm.automated.support.TestPersonPropertyId;
import gcm.automated.support.TestResourceId;
import gcm.scenario.PersonPropertyId;
import gcm.scenario.ResourceId;
import gcm.simulation.LabelSet;
import gcm.util.annotations.UnitTest;
import gcm.util.annotations.UnitTestMethod;

/**
 * Test class for {@link LabelSet}
 * 
 * @author Shawn Hatch
 *
 */
@UnitTest(target = LabelSet.class)

public class AT_LabelSet {
	private static SeedProvider SEED_PROVIDER;

	@BeforeClass
	public static void beforeClass() {
		SEED_PROVIDER = new SeedProvider(346345534578886785L);
	}

	/**
	 * Internal test(not part of public tests) to show that there are no large gaps
	 * in the seed cases generated by the SeedProvider.
	 */
	@AfterClass
	public static void afterClass() {
//		System.out.println(
//				AT_labelSet.class.getSimpleName() + " " + SEED_PROVIDER.generateUnusedSeedReport());
	}

	/**
	 * Tests {@linkplain LabelSet#getPersonPropertyIds()
	 */
	@Test
	@UnitTestMethod(name = "getPersonPropertyIds", args = {})
	public void testGetPersonPropertyIds() {
		final long seed = SEED_PROVIDER.getSeedValue(1);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		LabelSet.Builder builder = LabelSet.builder();

		for (int i = 0; i < 20; i++) {
			Set<PersonPropertyId> expectedPersonPropertyIds = new LinkedHashSet<>();

			for (TestPersonPropertyId testPersonPropertyId : TestPersonPropertyId.values()) {
				if (randomGenerator.nextBoolean()) {
					builder.setPersonPropertyLabel(testPersonPropertyId, "label");
					expectedPersonPropertyIds.add(testPersonPropertyId);
				}
			}

			LabelSet labelSet = builder.build();
			Set<PersonPropertyId> actualPersonPropertyIds = labelSet.getPersonPropertyIds();
			assertEquals(expectedPersonPropertyIds, actualPersonPropertyIds);
		}
	}

	/**
	 * Tests {@linkplain LabelSet#builder()
	 */
	@Test
	@UnitTestMethod(name = "builder", args = {})
	public void testBuilder() {

		LabelSet labelSet = //
				LabelSet.builder()//
						.setCompartmentLabel("compartment")//
						.setRegionLabel("region")//
						.setGroupLabel("group")//
						.setPersonPropertyLabel(TestPersonPropertyId.PERSON_PROPERTY_1, "prop1")//
						.setPersonPropertyLabel(TestPersonPropertyId.PERSON_PROPERTY_2, 45)//
						.setPersonResourceLabel(TestResourceId.RESOURCE2, 2342L)//
						.build();//

		assertNotNull(labelSet);

		// precondition tests
		assertException(() -> {
			LabelSet.builder()//
					.setPersonPropertyLabel(null, "label")//
					.build();//
		}, RuntimeException.class);

		assertException(() -> {
			LabelSet.builder()//
					.setPersonResourceLabel(null, "label")//
					.build();//
		}, RuntimeException.class);

	}

	/**
	 * Tests {@linkplain LabelSet#getPersonResourceIds()
	 */
	@Test
	@UnitTestMethod(name = "getPersonResourceIds", args = {})
	public void testGetPersonResourceIds() {
		final long seed = SEED_PROVIDER.getSeedValue(0);
		RandomGenerator randomGenerator = getRandomGenerator(seed);

		LabelSet.Builder builder = LabelSet.builder();

		for (int i = 0; i < 20; i++) {
			Set<ResourceId> expectedResourceIds = new LinkedHashSet<>();

			for (TestResourceId testResourceId : TestResourceId.values()) {
				if (randomGenerator.nextBoolean()) {
					builder.setPersonResourceLabel(testResourceId, "label");
					expectedResourceIds.add(testResourceId);
				}
			}

			LabelSet labelSet = builder.build();
			Set<ResourceId> actualResourceIds = labelSet.getPersonResourceIds();
			assertEquals(expectedResourceIds, actualResourceIds);
		}

	}

	/**
	 * Tests {@linkplain LabelSet#getGroupLabel()
	 */
	@Test
	@UnitTestMethod(name = "getGroupLabel", args = {})
	public void testGetGroupLabel() {
		Object expectedGroupLabel = "Group Label";

		LabelSet labelSet = //
				LabelSet.builder()//
						.setGroupLabel(expectedGroupLabel)//
						.build();//
		Object actualGroupLabel = labelSet.getGroupLabel();
		assertEquals(expectedGroupLabel, actualGroupLabel);
	}

	/**
	 * Tests {@linkplain LabelSet#getRegionLabel()
	 */
	@Test
	@UnitTestMethod(name = "getRegionLabel", args = {})
	public void testGetRegionLabel() {
		Object expectedRegionLabel = "Region Label";

		LabelSet labelSet = //
				LabelSet.builder()//
						.setRegionLabel(expectedRegionLabel)//
						.build();//
		Object actualRegionLabel = labelSet.getRegionLabel();
		assertEquals(expectedRegionLabel, actualRegionLabel);
	}

	/**
	 * Tests {@linkplain LabelSet#getCompartmentLabel()
	 */
	@Test
	@UnitTestMethod(name = "getCompartmentLabel", args = {})
	public void testGetCompartmentLabel() {
		Object expectedCompartmentLabel = "Compartment Label";

		LabelSet labelSet = //
				LabelSet.builder()//
						.setCompartmentLabel(expectedCompartmentLabel)//
						.build();//
		Object actualCompartmentLabel = labelSet.getCompartmentLabel();
		assertEquals(expectedCompartmentLabel, actualCompartmentLabel);
	}

	/**
	 * Tests {@linkplain
	 * LabelSet#getPersonPropertyLabel(gcm.scenario.PersonPropertyId)
	 */
	@Test
	@UnitTestMethod(name = "getPersonPropertyLabel", args = { PersonPropertyId.class })
	public void testGetPersonPropertyLabel() {
		LabelSet.Builder builder = LabelSet.builder();

		for (TestPersonPropertyId testPersonPropertyId : TestPersonPropertyId.values()) {
			builder.setPersonPropertyLabel(testPersonPropertyId, testPersonPropertyId.toString());
		}

		LabelSet labelSet = builder.build();

		for (TestPersonPropertyId testPersonPropertyId : TestPersonPropertyId.values()) {
			Object expectedPersonPropertyLabel = testPersonPropertyId.toString();
			Object actualPersonPropertyLabel = labelSet.getPersonPropertyLabel(testPersonPropertyId);
			assertEquals(expectedPersonPropertyLabel, actualPersonPropertyLabel);
		}
	}

	/**
	 * Tests {@linkplain LabelSet#getPersonResourceLabel(ResourceId)
	 */
	@Test
	@UnitTestMethod(name = "getPersonResourceLabel", args = { ResourceId.class })
	public void testGetPersonResourceLabel() {
		LabelSet.Builder builder = LabelSet.builder();

		for (TestResourceId testResourceId : TestResourceId.values()) {
			builder.setPersonResourceLabel(testResourceId, testResourceId.toString());
		}

		LabelSet labelSet = builder.build();

		for (TestResourceId testResourceId : TestResourceId.values()) {
			Object expectedResourceLabel = testResourceId.toString();
			Object actualResourceLabel = labelSet.getPersonResourceLabel(testResourceId);
			assertEquals(expectedResourceLabel, actualResourceLabel);
		}
	}

	/**
	 * Tests {@linkplain LabelSet#equals(Object)
	 */
	@Test
	@UnitTestMethod(name = "equals", args = { Object.class })
	public void testEquals() {
		LabelSet partitionQuery1 = LabelSet.builder()
				.setCompartmentLabel("compartment label").build();

		LabelSet partitionQuery2 = LabelSet.builder()
				.setCompartmentLabel("compartment label").build();

		LabelSet partitionQuery3 = LabelSet.builder()
				.setRegionLabel("compartment label").build();

		assertFalse(partitionQuery1 == partitionQuery2);
		assertTrue(partitionQuery1.equals(partitionQuery1));
		assertTrue(partitionQuery1.equals(partitionQuery2));
		assertTrue(partitionQuery2.equals(partitionQuery1));
		assertFalse(partitionQuery1.equals(partitionQuery3));

	}

	/**
	 * Tests {@linkplain LabelSet#hashCode()
	 */
	@Test
	@UnitTestMethod(name = "hashCode", args = {})
	public void testHashCode() {
		LabelSet partitionQuery1 = LabelSet.builder()
				.setCompartmentLabel("compartment label").build();

		LabelSet partitionQuery2 = LabelSet.builder()
				.setCompartmentLabel("compartment label").build();
		
		assertFalse(partitionQuery1 == partitionQuery2);
		assertEquals(partitionQuery1.hashCode(), partitionQuery2.hashCode());
	}

}
