package gcm.automated;

import static gcm.automated.support.EnvironmentSupport.getRandomGenerator;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.apache.commons.math3.random.RandomGenerator;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;

import gcm.automated.support.SeedProvider;
import gcm.util.Tuplator;
import gcm.util.Tuplator.Builder;
import gcm.util.annotations.UnitTest;
import gcm.util.annotations.UnitTestMethod;
import org.junit.jupiter.api.Test;

/**
 * Test class for {@link Tuplator}
 * 
 * @author Shawn Hatch
 *
 */
@UnitTest(target = Tuplator.class)
public class AT_Tuplator {
	private static SeedProvider SEED_PROVIDER;

	@BeforeAll
	public static void beforeClass() {
		SEED_PROVIDER = new SeedProvider(5082723487233498L);
	}

	/**
	 * Internal test(not part of public tests) to show that there are no large gaps
	 * in the seed cases generated by the SeedProvider.
	 */
	@AfterAll
	public static void afterClass() {
//		System.out.println(AT_Tuplator.class.getSimpleName() + " " + SEED_PROVIDER.generateUnusedSeedReport());
	}

	/**
	 * Tests {@link Tuplator#size()}
	 */
	@Test
	@UnitTestMethod(name = "size", args = {})
	public void testSize() {
		final long seed = SEED_PROVIDER.getSeedValue(0);
		RandomGenerator randomGenerator = getRandomGenerator(seed);
		for (int i = 0; i < 100; i++) {
			Builder builder = Tuplator.builder();
			int dimensionCount = randomGenerator.nextInt(4) + 1;
			int expectedSize = 1;
			for (int j = 0; j < dimensionCount; j++) {
				int dimSize = randomGenerator.nextInt(10) + 1;
				expectedSize *= dimSize;
				builder.addDimension(dimSize);
			}
			int actualSize = builder.build().size();
			assertEquals(expectedSize, actualSize);
		}
	}

	/**
	 * Tests {@link Tuplator#builder()}
	 */
	@Test
	@UnitTestMethod(name = "builder", args = {})
	public void testBuilder() {
		// covered by other tests
	}

	/**
	 * Tests {@link Tuplator#dimensions()}
	 */
	@Test
	@UnitTestMethod(name = "dimensions", args = {})
	public void testDimensions() {
		final long seed = SEED_PROVIDER.getSeedValue(1);
		RandomGenerator randomGenerator = getRandomGenerator(seed);
		for (int i = 0; i < 100; i++) {
			Builder builder = Tuplator.builder();
			int dimensionCount = randomGenerator.nextInt(4) + 1;
			for (int j = 0; j < dimensionCount; j++) {
				int dimSize = randomGenerator.nextInt(10) + 1;
				builder.addDimension(dimSize);
			}
			int actualDimensionCount = builder.build().dimensions();
			assertEquals(dimensionCount, actualDimensionCount);
		}
	}

	/**
	 * Tests {@link Tuplator#getTuple()}
	 */
	@Test
	@UnitTestMethod(name = "getTuple", args = { int.class, int[].class })
	public void testGetTuple() {

		Tuplator tuplator = Tuplator.builder().addDimension(2).addDimension(3).addDimension(5).build();

		int[] tuple = new int[tuplator.dimensions()];

		List<int[]> expectedArrays = new ArrayList<>();

		expectedArrays.add(new int[] { 0, 0, 0 });
		expectedArrays.add(new int[] { 1, 0, 0 });
		expectedArrays.add(new int[] { 0, 1, 0 });
		expectedArrays.add(new int[] { 1, 1, 0 });
		expectedArrays.add(new int[] { 0, 2, 0 });
		expectedArrays.add(new int[] { 1, 2, 0 });
		expectedArrays.add(new int[] { 0, 0, 1 });
		expectedArrays.add(new int[] { 1, 0, 1 });
		expectedArrays.add(new int[] { 0, 1, 1 });
		expectedArrays.add(new int[] { 1, 1, 1 });
		expectedArrays.add(new int[] { 0, 2, 1 });
		expectedArrays.add(new int[] { 1, 2, 1 });
		expectedArrays.add(new int[] { 0, 0, 2 });
		expectedArrays.add(new int[] { 1, 0, 2 });
		expectedArrays.add(new int[] { 0, 1, 2 });
		expectedArrays.add(new int[] { 1, 1, 2 });
		expectedArrays.add(new int[] { 0, 2, 2 });
		expectedArrays.add(new int[] { 1, 2, 2 });
		expectedArrays.add(new int[] { 0, 0, 3 });
		expectedArrays.add(new int[] { 1, 0, 3 });
		expectedArrays.add(new int[] { 0, 1, 3 });
		expectedArrays.add(new int[] { 1, 1, 3 });
		expectedArrays.add(new int[] { 0, 2, 3 });
		expectedArrays.add(new int[] { 1, 2, 3 });
		expectedArrays.add(new int[] { 0, 0, 4 });
		expectedArrays.add(new int[] { 1, 0, 4 });
		expectedArrays.add(new int[] { 0, 1, 4 });
		expectedArrays.add(new int[] { 1, 1, 4 });
		expectedArrays.add(new int[] { 0, 2, 4 });
		expectedArrays.add(new int[] { 1, 2, 4 });

		for (int i = 0; i < tuplator.size(); i++) {
			tuplator.getTuple(i, tuple);
			assertTrue(Arrays.equals(expectedArrays.get(i), tuple));
		}

	}

}
